### DISCUSSION TITLE
Only params and metrics showing in UI, not model

### DISCUSSION THREAD

**Discussion by Hoff-S** [mlflow/mlflow#12438] [Q&A]
Hi there,

I'm novice and I'm trying to do some stuff. Sorry for the lack of good practice ...

# I have a container with an MLFLOW server running. 

## The docker image was built according to this dockerfile :

>FROM ubuntu:22.04 
>RUN apt-get update && apt-get install python3-pip -y && pip3 install mlflow
>WORKDIR /app
>EXPOSE 5000
>VOLUME /app/mlruns
>CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--default-artifact-root", "/app/mlruns", "--app-name", "basic-auth"]

## I lauch it with this command : 

>docker run -p 8080:5000 -v ${pwd}/mlruns:/app/mlruns mlflow_server

# I have an other container to train a SARIMA model.

## Here is the Dockerfile for this one :

>FROM ubuntu:22.04
>WORKDIR /app
>COPY model_training.py /app/model_training.py
>COPY requirements.txt /app/requirements.txt
>RUN apt-get update && apt-get install python3-pip -y && pip3 install -r requirements.txt
>VOLUME /app/mlruns
>CMD python3 model_training.py 

## The model_training.py script mission is to train a model and export metrics, model and params to the MLFLOW server :
```
API_URL = os.environ.get('API_URL') 
mlflow_tracking_uri = os.environ.get('MLFLOW_TRACKING_URI') 

-----

mlflow.set_tracking_uri(mlflow_tracking_uri)
mlflow.set_experiment("Crypto_Models")
run_name = "first_run"

print(f"Current working directory: {os.getcwd()}")

with mlflow.start_run(run_name=run_name) as run:
    artifact_path = "model"

    # Log the trained model
    mlflow.statsmodels.log_model(best_model, artifact_path=artifact_path)
    print(f"Logging model to {artifact_path}")

    # Verify that the model was logged
    local_model_path = mlflow.get_artifact_uri(artifact_path)
    print(f'Model logged at: {local_model_path}')

    # Check if the artifact path is valid and exists
    if os.path.exists(artifact_path):
        print(f"Artifact path {artifact_path} exists.")
    else:
        print(f"Artifact path {artifact_path} does not exist.")

    # Save parameters
    mlflow.log_params({
        "lambda": lmbda,
        "order_p": best_param[0],
        "order_d": d,
        "order_q": best_param[1],
        "seasonal_order_P": best_param[2],
        "seasonal_order_D": D,
        "seasonal_order_Q": best_param[3]
    })

    # Save metrics
    mlflow.log_metric("yesterday_close_price_value", df_day['close_price'].iloc[-1])
```

# This last container and other services are launch with this dockerfile, this is only the training model part :
```
  model_training:
    image: model_training:latest
    container_name: model_training
    depends_on:
      - cryptobot_api
    environment:
      - API_URL=cryptobot_api
      - MLFLOW_TRACKING_URI=${IP_ADDRESS}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
    volumes:
      - ../mlruns:/app/mlruns
    networks: 
      - compose-network

networks:
  compose-network:
    name: my_network

volumes:
  mlruns:
```
I have the same mlruns folder in my mlflow container, my model_training container and my local directory.
When I start a new run, a new run_id is created, I can get the params, the metrics but not the model. In the "model" part of the UI, there is a link, but nothing inside. Nothing inside mlruns artifacts in my local directory ... Where am I mistaken ? 

Here are the logs : 
```
model_training    | Current working directory: /app                                                                                                          
model_training    | Logging model to model
model_training    | Model logged at: file:///C:/Users/apsho/Project/mlruns/594249274040179504/88a91945f39541018dc0fad3ff88b75e/artifacts/model                                                                                                                                 
model_training    | Artifact path model does not exist.
model_training exited with code 0
```

This is the proof something happened about model saving :
![Pic2](https://github.com/mlflow/mlflow/assets/150697181/88d3e8d6-fd24-4ea9-8055-38d92c1da90c)

But the folder is empty :
![Pic1](https://github.com/mlflow/mlflow/assets/150697181/dfd9ed8e-2df3-40bc-ab61-342466f53346)
