### DISCUSSION TITLE
log_artifacts doesn't save file to a pod

### DISCUSSION THREAD

**Discussion by serdar-akyol** [mlflow/mlflow#15309] [Q&A]
I have a mlflow server running on minikube. My config yaml as shown as below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.17.2
        ports:
          - containerPort: 5000
        command: ["sh", "-c"]
        args:
          - |
            pip install psycopg2-binary boto3 && mlflow server --default-artifact-root file:/mlflow/artifacts --serve-artifacts
        env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: "postgresql://user:password@postgresql/mlflow_db"
          - name: MLFLOW_PORT
            value: "5000"
          - name: MLFLOW_HOST
            value: "0.0.0.0"
          - name: MLFLOW_TRACKING_LOG_LEVEL
            value: DEBUG
        volumeMounts:
          - name: mlflow-data
            mountPath: /mlflow/artifacts
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
```
my mlflow pod is running on **http://10.XXX.XXX.XXX:5000** and I am able to see my mlfow UI on this url. However, when I try to save a small txt file, it looks like all well but the artifact is not exist on /mlflow/artifacts directory inside mlflow's pod. Here is my code
```
def save_txt():
    url = "http://10.XXX.XXX.XXX:5000"
    mlflow.set_tracking_uri(uri=url)
    run = mlflow.active_run()
    print(run.info.artifact_uri)

    with mlflow.start_run():
        with open("test.txt", "w") as f:
            f.write("hello")
        mlflow.log_artifact("test.txt")

if __name__ == "__main__":
    save_txt()
```
How can I save **test.txt** file inside mlflow's pod and see that file on /mlflow/artifacts directory?
