### DISCUSSION TITLE
How to restore code of pyfunc class in MlFlow?

### DISCUSSION THREAD

**Discussion by pjman007** [mlflow/mlflow#6473] [Q&A]
I have lost a code of my pyfunc class which I uploaded to MlFlow. Model is working on a production but via MLFlow UI I can't get code view of model class. For some R models I can get code class using load_model. After call this method I get the whole code view of class which is uploaded to MlFlow. Unfortunately, it doesnt work the same way in python. All files are inside hdfs directory of MLFlow.

```
import mlflow
logged_model = '"file:///var/mm/mlflow/artifacts/***/*******/artifacts/my_model_name'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)
```

After invoking to loaded_model I get only some not important infos about model:

```
mlflow.pyfunc.loaded_model:
  artifact_path: my_model_name
  flavor: mlflow.pyfunc.model
  run_id: *****
```

How can I check the code of the class which was uploaded to MLFlow earlier?
