### DISCUSSION TITLE
storageUri for a model in the model registry? (kserve)

### DISCUSSION THREAD

**Discussion by tamis-laan** [mlflow/mlflow#7157] [Q&A]
I'm using mlflow for experiment tracking and as a model registry. For deployment I want to use kserve. Kserve uses the following spec for model deployment:
``` yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```
As you can see a storageUri is required where knative can fetch the model from. I have created a model, trained it and registered the model as version 1 in the model repository. I have also moved the model to production. How can I get the link, i.e. storageUri for the model? I would like to get this link from the GUI and programmatically for CI/CD jobs.

I can retrieve a link from mlflow like this one `mlflow-artifacts:/0/87dde16bdaf54cf2a200f4cf2d3b5728/artifacts/model` but how can I download the model without using python but as a simple get request?
