### ISSUE TITLE
R tracking does not log params given in command line correctly (version 0.9.0)

### ISSUE THREAD

**Issue by bernhard-42** [mlflow/mlflow#1014]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes, see below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **MLflow installed from (source or binary)**: 
   Note: In 0.8.2 R tracking is broken, hence I tried this approach with latest master
   $ git clone https://github.com/mlflow/mlflow.git
   $ cd mlflow/mlflow/R
   $ R CMD build mlflow
   $ R
   > install.packages("./mlflow_0.9.0.tar.gz")
- **MLflow version (run ``mlflow --version``)**: 0.9.0 (master, with pip install from github)
- **Python version**: 3.7.2
- **npm version (if running the dev UI)**: n/a
- **Exact command to reproduce**: see below

### Describe the problem

I started with the wine_r project and reduced the source files to a minimum to show the issue:
 
MLproject:
```
name: mlflow-r

entry_points:
  main:
    parameters:
      alpha: float
      lambda: float
    command: "R -f train.R"
```

**TEST 1**

train.R
```
library(mlflow)
alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")

with(mlflow_start_run(), {
  message("nop")
})
```

Execute:
```
$ mlflow run . -P alpha=0.14 -P lambda=0.14 --experiment-id=$EXID
nop
```

This creates a run in the tracking server with `alpha=0.14` and `lambda=0.14`

**TEST 2**

train.R
```
library(mlflow)

alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")

with(mlflow_start_run(), {
  message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")

  mlflow_log_param("alpha", alpha)
  mlflow_log_param("lambda", lambda)
})
```

Execute:
```
$ mlflow run . -P alpha=0.14 -P lambda=0.14 --experiment-id=$EXID
Elasticnet model (alpha=0.5, lambda=0.5):
```

The output shows `0.5` while again there is is a run with `alpha=0.14` and `lambda=0.14` on the tracking server. 
So there are two things that don't work as I expected:

1. `alpha <- mlflow_param("alpha", 0.5, "numeric")` does not use `-P` parameter values, since the message output shows `0.5` for both params
2. `mlflow_log_param` should set alpha and lambda to `0.5` which it does not

Am I doing something wrong here?

**Comment by bernhard-42** [comment]
One part is solved, MLproject file was wrong, it needs to be 

```
name: mlflow-r

entry_points:
  main:
    parameters:
      alpha: float
      lambda: {type: float, default: 0.1}
    command: "Rscript -e 'mlflow::mlflow_source(train.R)' --args --alpha={alpha} --lambda={lambda}"
```

However, it is strange that the mlflow python scripts tracks the command line parameters, even if I don't track them in the R code.
