### ISSUE TITLE
[BUG] Unable to connect to deployment server for UI prompt engineering

### ISSUE THREAD

**Issue by harshithere** [mlflow/mlflow#10728]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

2.9.2

### System information

- **OS Platform: Mac 13.0.1 (Ventura)**:
- **Python: 3.9**:

### Describe the problem

Post launching the ML deployment server, the MLflow server can't communicate with it to obtain the necessary endpoints needed for hitting an external LLM (Openai). This can be seen in the fact that model dropdown in the prompt engineering tab is empty even after adding certain endpoints in a `config.yaml` file as described in the steps.

The endpoints can be reached when called via a curl call or within a .py file. 

### Steps to reproduce the bug

**Launch the deployment server**
1. export OPENAI_API_KEY=<your_api_key_here>
2. mlflow deployments start-server --config-path config.yaml --7000

**Launch MLflow**
1. export MLFLOW_DEPLOYMENTS_TARGET="http://127.0.0.1:7000"
2. mlflow server --port 5000

Move to the using prompt engineering tab via the 'new run' button
Check the models dropdown for available options (shows none)

### Code to generate data required to reproduce the bug

Contents of the config.yaml file

```
endpoints:
  - name: completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY

```
