### ISSUE TITLE
[BUG] Recipes: last experiment runs exceed range of values of hyperparameter tuning

### ISSUE THREAD

**Issue by johannes-hoeffer** [mlflow/mlflow#11460]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.4.2

### System information

- **OS Platform and Distribution**: Azure Databricks Runtime 13.3 LTS ML
- **Python version**: 3.10.12

### Describe the problem

I'm currently working on a project using MLFlow Recipes. So far everything went rather smoothly, however I encountered some strange behavior by MLFlow. In my experiments, I use an lgbm classifier alongside hyperparameter tuning (hyperopt) and early stopping. Therefore I defined ranges of acceptable values for some parameters. 

Training goes well so far but looking at the experiment runs, I saw that max_depth is always logged as -1 in the last run before training ends, even though the range for max_depth is [1, 3]. Is this some sort of standard behavior, a bug or am I doing something wrong?

I also noticed that in cases when the last run turns out to beat the previously best model, it's being registered without going through another early stopping cycle (ten iterations). Maybe this has something to do with it, maybe it's another problem?

### Tracking information

```shell
MLflow version: 2.4.2
Tracking URI: databricks
Artifact URI: dbfs:/databricks/mlflow-tracking/[...]/artifacts
```

### Code to reproduce issue

Here's what the training section of my `recipe.yaml` looks like. 
```
train:
  predict_scores_for_all_classes: True
  predict_prefix: "predicted_"
  using: "custom"
  estimator_method: estimator_fn
  estimator_params:
    random_state : 42
  tuning:
    enabled: True
    algorithm: "hyperopt.rand.suggest"
    max_trials: 100
    parallelism: 1
    early_stop_fn : early_stopping
    parameters:
        alpha:
          distribution: "uniform"
          low: 0.0001
          high: 0.1
        learning_rate:
          distribution: "uniform"
          low: 0.0001
          high: 0.1
        max_depth:
          distribution: "uniformint"
          low: 1
          high: 3
        n_estimators:
          distribution: "uniformint"
          low: 1000
          high: 10000
```

That's the code of my `train.py` step.
```
from typing import Dict, Any


def estimator_fn(estimator_params: Dict[str, Any] = None):
    """
    Returns an *unfitted* estimator that defines ``fit()`` and ``predict()`` methods.
    The estimator's input and output signatures should be compatible with scikit-learn
    estimators.
    """
    from lightgbm import LGBMClassifier

    if estimator_params is None:
        estimator_params = {}
    return LGBMClassifier(**estimator_params)

def early_stopping(*args):
    from hyperopt.early_stop import no_progress_loss
    return no_progress_loss(10)(*args)
```

And finally, the reciipe calls in `databricks.py`.

```
import json 
import mlflow
from mlflow.recipes import Recipe

r = Recipe(profile="databricks")
r.clean()
# r.inspect()
try:
    r.run("ingest")
except mlflow.exceptions.MlflowException:
    dbutils.notebook.exit(json.dumps({
        'error': 406,
        'errorMsg': 'No training data available'
    }))
r.run("split")
r.run("transform")
r.run("train")
```

### Stack trace

Training works fine, but once Early stopping occurs, one last run is triggered with hyperparameters, which exceed my defined value range, eg.g. max_depth = -1. (perhaps some sort of default values?)
![Annotation 2024-03-19 113711](https://github.com/mlflow/mlflow/assets/70543510/bc37c5a9-6f43-43fb-b715-0e1dbf783e8c)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations
