### ISSUE TITLE
ImportError: cannot import name 'extract_span_inputs_outputs' from 'mlflow.tracing.utils'[BUG]

### ISSUE THREAD

**Issue by obiii** [mlflow/mlflow#12459]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Azure Machine Learning

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow: 2.13.2
- mlflow-skinny: 2.13.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **Python version**: 3.10
 

### Describe the problem

While running the AML pipelines we get this error:

> Traceback (most recent call last):
>   File "/opt/miniconda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/miniconda/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/mnt/azureml/cr/j/63ac8ab7a9db4c4c939627d2fe3e5eb2/exe/wd/train/main_ts_models.py", line 11, in <module>
>     import mlflow
>   File "/opt/miniconda/lib/python3.10/site-packages/mlflow/__init__.py", line 109, in <module>
>     from mlflow.tracing.fluent import (
>   File "/opt/miniconda/lib/python3.10/site-packages/mlflow/tracing/fluent.py", line 26, in <module>
>     from mlflow.tracing.utils import (
> ImportError: cannot import name 'extract_span_inputs_outputs' from 'mlflow.tracing.utils' (/opt/miniconda/lib/python3.10/site-packages/mlflow/tracing/utils/__init__.py)

It happens with `import mlflow`

The environments that we build have following dependencies:

```
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip==23.3.1
  - pip:
    - azureml-sdk==1.54.0
    - azureml-core==1.54.0
    - adlfs==2023.12.0
    - cloudpickle==2.2.1
    - fs==2.4.16
    - fsspec==2023.12.1
    - numba==0.58.1
    - numpy==1.23.5
    - pandas==2.1.2
    - polars==0.20.3
    - pyarrow==14.0.2
    - statsforecast==1.6.0
    - statsmodels==0.14.1
    - seaborn==0.13.0
    - utilsforecast==0.0.24
    - deltalake==0.15.1
    - azure-storage-file-datalake==12.14.0
    - azure-ai-ml==1.16.1
    - azure-identity==1.16.1
    - azure-keyvault==4.2.0
    - mltable
    - mlflow==2.13.2
    - mlflavors==0.1.0
    - azureml-mlflow==1.56.0
  - conda:
    - conda=23.11.0
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
