### ISSUE TITLE
How can I restore my experiments to a new mlflow server, when the old one has been deleted?

### ISSUE THREAD

**Issue by johnf1004** [mlflow/mlflow#14081]
Hi,

I am hosting Mlflow with docker-compose. One service for MLflow, one for sqlite backend. I wanted to update the MLflow version, so I stopped & removed the Mlflow service, changed from adacotechjp/mlflow:2.3.1 to adacotechjp/mlflow:2.7.1, then rebuilt the service with `docker-compose up`.
```

services:
  sqlite:
    image: keinos/sqlite3:3.42.0
    hostname: sqlite
    container_name: sqlite
    stdin_open: true
    tty: true
    ports:
      - "8191:8191"
    volumes:
      - ./sqlitedb:/root/db

  mlflow:
    image: adacotechjp/mlflow:2.3.1
    hostname: mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_DEFAULT_ARTIFACT_ROOT: "gs://mlflow-bucket-16"
      MLFLOW_BACKEND_STORE_URI: "sqlite:///mlrunsdb.db"
    depends_on:
      - sqlite
```
I thought this would be a clean way to simply change the version, and all of my experiments and runs would persist. Unfortunately, they have vanished from the UI. The artifacts still exist in my GCS backend, and I didnt touch my sqlite service.

How can I restore my experiments to the new mlflow server, when the old one has been deleted?
