### ISSUE TITLE
[BUG]  CANNOT download artifacts from MLflow UI

### ISSUE THREAD

**Issue by ZOU-Da** [mlflow/mlflow#15245]
### MLflow version

2.21.2

### System information

- **OS Platform and Distribution**: Linux Ubuntu 20.04
- **Python version**: 3.10.16

### Describe the problem

I have installed mlflow on a training server, used postgre as backend store and minio as artifacts store. The two databases are installed in the same training server. I followed this [tutorial](https://mlflow.org/docs/latest/tracking/tutorials/remote-server/) to setup the environment. Here is the `compose.yaml` and `cmd`. Now the training is running, the metrics and artifacts can be watched in mlflow UI, but in the `Artifacts` tab, I cannot preview the model file and the logged text artifact file, and cannot download the model file. But I can log into the MinIO web and download the files. Is there something wrong when I start the mlflow server with `--artifacts-destination s3://bucket \`

### Steps to reproduce the bug

1. install postgre and minio with docker compose
2. start the mlflow server

### Code to generate data required to reproduce the bug

Here is the `compose.yaml` and `bash`.
```yaml
services:
  # PostgreSQL database
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflowdb
    ports:
      - 5432:5432
    volumes:
      - /mnt/store/install/postgres-data:/var/lib/postgresql/data
  # MinIO server
  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/store/install/minio-data:/data
  # Create a bucket named "bucket" if it doesn't exist
  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 minio_user minio_password &&
      if ! mc ls minio/bucket; then
        mc mb minio/bucket
      else
        echo 'bucket already exists'
      fi
      "
```

```bash
export MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
export AWS_ACCESS_KEY_ID=minio_user
export AWS_SECRET_ACCESS_KEY=minio_password

mlflow server \
  --backend-store-uri postgresql://user:password@localhost:5432/mlflowdb \
  --artifacts-destination s3://bucket \
  --host 0.0.0.0 \
  --port 5000
export MLFLOW_TRACKING_URI=http://127.0.0.1:5000
python train.py
```
