### ISSUE TITLE
Does mlflow  support DAG workflow？

### ISSUE THREAD

**Issue by frankzqy** [mlflow/mlflow#1563]
MLFlow 怎么支持DAG workflow，if ture，please show an example

**Comment by lorenzwalthert** [comment]
I also wondered and I don't think so. it would be amazing if there would be support for this. The `MLproject` file could host a `dependencies` key like a `MAKE` file.

```yaml
entry_points:
  prepare_clean:
    parameters: 
      y: {type: string, default: "3"}
    command: ...
  clean:
    parameters: 
      x: {type: string, default: "new"}
    command: ...
    dependencies: 
    - prepare_clean

```

Supporting this would be quite an effort though I think. I wonder if there are other ways to combine the strengths of DAG computing with mlflow, notably integrate it in existing workflow managers.
