### ISSUE TITLE
[BUG] Error when using gemini-2.0-flash in prompt engineering ui "The chat route is not implemented for Gemini models."

### ISSUE THREAD

**Issue by mfiqihalayubi** [mlflow/mlflow#15641]
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.22.0
- Tracking server: 2.22.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3..11.5
- **yarn version, if running the dev UI**: 

### Describe the problem

I have deployed MLflow and AI Gateway using Docker to try out the Prompt Engineering UI feature. I am able to test prompts in the Prompt Engineering UI with the GPT provider, but not with Gemini (both with chat and completions). When using Gemini, I get the following error message in the UI:

MLflow deployment returned the following error:
"Deployments proxy request failed with error code 501. Error message: {"detail":"The chat route is not implemented for Gemini models."}"

My question is: Does MLflow AI Gateway and the Prompt Engineering UI feature already support models from the Gemini provider?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
endpoints:
  - name: openai-chat-4o-mini
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4o-mini
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: openai-chat-4o
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4o
      config:
        openai_api_key: $OPENAI_API_KEY
        
  - name: openai-chat-4o-mini-completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4o-mini
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: openai-chat-4o-completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4o
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: gemini-2.0-flash-completions
    endpoint_type: llm/v1/completions
    model:
      provider: gemini
      name: gemini-2.0-flash
      config:
        gemini_api_key: $GEMINI_API_KEY

  - name: gemini-2.0-flash-chat
    endpoint_type: llm/v1/chat
    model:
      provider: gemini
      name: gemini-2.0-flash
      config:
        gemini_api_key: $GEMINI_API_KEY
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
