### ISSUE TITLE
Update astral-sh/setup-uv step in .github/actions/setup-python/action.yml

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#15878]
The `astral-sh/setup-uv` step in `.github/actions/setup-python/action.yml` is currently pinned to version `v3.2.4` and installs `uv` version `0.5.4`:

```yaml
- uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4
  with:
    version: 0.5.4
```

Please update both the `setup-uv` action version and the `uv` version to the latest stable releases.
