### ISSUE TITLE
Add a rule in .github/policy.rego to enforce that github actions is pinned by full commit SHA

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#15977]
`github/policy.rego` define rules for github action config files. To enhance security, we should add a rule to enforce that gi

```yml
# bad
- uses: actions/checkout@v4

# good
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

# exception
# actions stariting with './.github' should be ignored
- uses: ./.github/...
```
