### ISSUE TITLE
Deployment of Tracking Server to Google Kubernetes Engine: Site Cannot Be Reached

### ISSUE THREAD

**Issue by rileyhun** [mlflow/mlflow#2299]
I'm trying to host an MLFlow Tracking Server remotely on Google Kubernetes Engine. After deploying the service, I don't see an errors being logged, so I believe deployment was a success. 

However, when I go into the Public IP Address, it says the site cannot be reached. Does anyone have an insight on what's happening here? Any help would be greatly appreciated!

**DockerFile**

   ```
 FROM python:3-onbuild
    
    LABEL maintainer='rihun@cisco.com'
    
    RUN mkdir /mlflow
    ADD . /mlflow
    
    WORKDIR /mlflow
    
    RUN pip3 --no-cache-dir install -r requirements.txt
    
    EXPOSE 5000
    
    RUN chmod u+x ./start.sh
    ENTRYPOINT ["./start.sh"]
```

**Deployment Yaml File**

   ```
 apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mlflow-tracking-server-deploy
      labels:
        app: mlflow-tracking-server
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mlflow-tracking-server
      template:
        metadata:
          labels:
            app: mlflow-tracking-server
        spec:
          # This section describes the containers that make up the deployment
          containers:
            - name: mlflow-tracking-server
              image: gcr.io/dao-aa-poc-uyim/mlflow-tracking-server
    #          ports:
    #            - containerPort: 5000
              # Set env variables used for Postgres Connection
              env:
                - name: GCLOUD_SERVICE_KEY_ENC
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-env-secret
                      key: GCLOUD_SERVICE_KEY_ENC
                - name: GCP_STORAGE_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-env-secret
                      key: GCP_STORAGE_BUCKET
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-env-secret
                      key: DB_USER
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-env-secret
                      key: DB_PASS
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-env-secret
                      key: DB_NAME
            # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
            # project, the region of your Cloud SQL instance and the name
            # of your Cloud SQL instance. The format is $PROJECT:$REGION:$INSTANCE
            - name: cloudsql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.11
              command: ["/cloud_sql_proxy",
                        "-instances=dao-aa-poc-uyim:us-east1:ailab=tcp:5432",
                        "-credential_file=/secrets/cloudsql/credentials.json"]
              volumeMounts:
                - name: my-secrets-volume
                  mountPath: /secrets/cloudsql
                  readOnly: true
          volumes:
            - name: my-secrets-volume
              secret:
                secretName: cloudsql-instance-credentials
```

**Shell Script**

 ```

    set -ex
    
    if ! ([ -z "${GCLOUD_SERVICE_KEY_ENC}" ] || [ -z "${GCP_STORAGE_BUCKET}" ]); then
      echo  "Creating experiment"
      NAME="Experiment1"
      echo $GCLOUD_SERVICE_KEY_ENC | base64 --decode > ~/secrets_dec.json
      export GOOGLE_CLOUD_KEYFILE_JSON=~/secrets_dec.json
      if ! [ -z "${EXPERIMENT_NAME}" ]; then
        NAME=$EXPERIMENT_NAME
        cd /mlflow
        mlflow experiments create --artifact-location gs://$GCP_STORAGE_BUCKET $NAME
      fi
    else
      echo "Not found environment variables"
    fi
    
    mlflow server \
    #    --file-store /mlflow/feature_pipeline_runs \
        --host 0.0.0.0 \
        --backend_store_uri postgresql+psycopg2://$DB_USER:$DB_PASS@$127.0.0.1:5432/$DB_NAME \
        --default-artifact-root gs://$GCP_STORAGE_BUCKET \
    #    --port 5000
```

**Here's the Log:**

> [2020-01-13 17:34:36 +0000] [15] [INFO] Starting gunicorn 20.0.4
> [2020-01-13 17:34:36 +0000] [15] [INFO] Listening at: http://127.0.0.1:5000 (15)
> [2020-01-13 17:34:36 +0000] [15] [INFO] Using worker: sync
> [2020-01-13 17:34:36 +0000] [18] [INFO] Booting worker with pid: 18
> [2020-01-13 17:34:36 +0000] [19] [INFO] Booting worker with pid: 19
> [2020-01-13 17:34:36 +0000] [20] [INFO] Booting worker with pid: 20
> [2020-01-13 17:34:36 +0000] [22] [INFO] Booting worker with pid: 22
