### ISSUE TITLE
[FR] Use existing conda.yaml to log model

### ISSUE THREAD

**Issue by adriangonz** [mlflow/mlflow#2413]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Right now, by default, when a model gets saved using `log_model()` the [`conda.yaml` environment always falls back to a pre-defined one](https://www.mlflow.org/docs/latest/python_api/mlflow.spark.html#mlflow.spark.log_model). However, for cases where there is already a local `conda.yaml` environment defined it could be good to use the existing one instead.

### Motivation
Let's say we've got a MLflow project, with a `MLproject` and `conda.yaml` files defining the environment required for the model to run. Based on this, we can run `mlflow run ...` on the model folder and then save the trained model using `log_model()`. However, if we look into what MLflow generates in the `/mlruns/.../artifacts` folder, the `conda.yaml` environment will be just a default one instead of the existing `conda.yaml` file.

For example, imagine that we've got the following `conda.yaml` environment already defined for our model:

```yaml
name: model-a
channels:
  - defaults
dependencies:
  - python=3.6
  - pyspark=2.4.0
  - scikit-learn=0.22.1
  - openjdk=8.0.152
  - pip:
      - mlflow==1.6.0
```

By default, when we use `mlflow.spark.log_model()`, the generated `conda.yaml` will always have only `python`, `pyspark` and `mlflow` as listed dependencies:

```yaml
channels:
  - defaults
dependencies:
  - python=3.6.10
  - pyspark=2.4.4
  - pip:
    - mlflow
name: mlflow-env
```

### Proposed Changes
Change the current behaviour of the `log_model()` method so that it checks first if there is an existing `conda.yaml` defined.
