### ISSUE TITLE
[BUG] Pyfunc artifact paths created on Windows use Windows path separators.

### ISSUE THREAD

**Issue by mikeoconnor0308** [mlflow/mlflow#2759]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.6
- **Exact command to reproduce**:
N/A

### Describe the problem
Creating pyfunc model on windows using the `artifacts` arguments results in an MLModel file with windows separators in the paths: 

```
flavors:
  python_function:
    artifacts:
      artifact:
        path: artifacts\some_artifact
        uri: some_artifact
    cloudpickle_version: 1.3.0
    env: conda.yaml
    loader_module: mlflow.pyfunc.model
    python_model: python_model.pkl
    python_version: 3.6.10
utc_time_created: '2020-04-28 15:59:25.211458'
```

The problem with this is portability. E.g. running a docker container fails miserably. 

The fix is probably to always use forward slashes for this. 

### Code to reproduce issue
```python
import mlflow.pyfunc

class PythonModelWrapper(mlflow.pyfunc.PythonModel):
    pass

artifact_path='some_artifact'
with open(artifact_path, 'w') as f:
    f.write('example')

artifacts = {
    'artifact' : artifact_path
}

mlflow_pyfunc_model_path = "mlflow_pyfunc"
mlflow.pyfunc.save_model(
        path=mlflow_pyfunc_model_path, python_model=PythonModelWrapper(), artifacts=artifacts)
```
