### ISSUE TITLE
How to specify which model flavor to use for serving

### ISSUE THREAD

**Issue by mlwkshops** [mlflow/mlflow#2798]
How can one specify which flavor to use while running
```python
mlflow models serve -m runs:/my-run-id/model-path
```
There is no flavor argument listed. And the default is `python_function`. How can I make it select a particular flavor e.g. `sklearn`? 

Here is the MLModel file for reference.
```yaml
artifact_path: model
flavors:
  python_function:
    data: model.pkl
    env: conda.yaml
    loader_module: mlflow.sklearn
    python_version: 3.6.3
  sklearn:
    pickled_model: model.pkl
    serialization_format: cloudpickle
    sklearn_version: 0.21.3
run_id: eb1e46b7b5954f88bc231d273dcd6357
utc_time_created: '2020-05-07 11:10:27.508274'
```
