### ISSUE TITLE
[FR] - option to specify conda / docker environments per entry point

### ISSUE THREAD

**Issue by jkthompson** [mlflow/mlflow#2877]
**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
I would like the option to specify a different environment for some or all of the entry points in my mlflow project.  Currently I can only specify a single environment per mlflow project.  

## Motivation
- What is the use case for this feature?  
I have a multi-step workflow with at least two steps: 1) data prep and 2) model training.  Both steps are fairly complex, developed by different teams, and have different overlapping dependencies.  I would like the teams to be able to manage their conda environments independently without having to reach consensus on specific versions of overlapping dependencies.
- Why is this use case valuable to support for MLflow users in general?
I imagine this is a common pain point in developing multi-step workflows when there are multiple developers working on different parts of the workflow.
- Why is this use case valuable to support for your project(s) or organization?
It would make our ml pipeline code more modular and easier to maintain.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
Best I can tell, the only way to achieve multiple environments per entry point is to set up multiple mlflow projects for each each step.  However this makes the code more complex to understand what is going on.  I would like to specify all of my entry points in a single MLProject file.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details
Allow user to specify conda_env or docker_env within an entry point in the MLProject file. Add env member variables ('docker_env', 'conda_env_path') to EntryPoint class.  In project._run() check for entry_point env variables.  If env variables are set, override project env before launching run.

`name: My Project

conda_env: my_env.yaml
# Can have a docker_env instead of a conda_env, e.g.
# docker_env:
#    image:  mlflow-docker-example

entry_points:
  main:
    parameters:
      data_file: path
      regularization: {type: float, default: 0.1}
    command: "python train.py -r {regularization} {data_file}"
  validate:
    conda_env: my_validate_env.yaml
    # Can have a docker_env instead of a conda_env, e.g.
    # docker_env:
    #    image:  validate_mlflow-docker-example
    parameters:
      data_file: path
    command: "python validate.py {data_file}"`

**Comment by Zethson** [comment]
I also wanted to request this already, but not flood the issue tracker :) So strong :+1: from me!

This is especially useful, since for example bioconda builds one docker container per tool (automatically), which could then be used in a (future) DAG for multistep projects.

This would modularize and improve reproducibility for complex multistep projects, which require complex pre/post processing (before/after machine learning)

**Comment by mparkhe** [comment]
This is a good idea. Would be great big project for someone from the MLflow community to contribute. Since this is a sizable project, we would appreciate starting with a short design that spells out different scenarios and expected behavior.

**Comment by jkthompson** [comment]
I'd like to give this a try.  Below is my first attempt at a design.  Feedback would be appreciated.  Thanks.

# Expected Behavior
1. Users are able to optionally add docker or conda environments ('conda_env:' or 'docker_env:') within individual entry points, inside an MLProject file.

Docker Example 

MLProject:
```yml
name: docker-example

docker_env:
  image:  mlflow-docker-example

entry_points:
  main:
    parameters:
      alpha: float
      l1_ratio: {type: float, default: 0.1}
    command: "python train.py --alpha {alpha} --l1-ratio {l1_ratio}"
  tf2_training:
    docker_env:
      image: docker-tf2
    parameters:
      alpha: float
      l1_ratio: {type: float, default: 0.1}
    command: "python train.py --alpha {alpha} --l1-ratio {l1_ratio}"
```
Conda Example

MLProject:
```yml
name: My Project

conda_env: my_env.yaml

entry_points:
  main:
    parameters:
      data_file: path
      regularization: {type: float, default: 0.1}
    command: "python train.py -r {regularization} {data_file}"
  validate:
    conda_env: validate_env.yaml
    parameters:
      data_file: path
    command: "python validate.py {data_file}"
```
2. If specified, the local entry point environment takes precedence over the project level environment.  If not specified, the project level environment is used.

3. Entry point environments are validated in the same way as project level environments and the same rules apply.

4. Mixed use of conda and docker entry point environments within the same MLProject file is allowed as long as only one environment is specified per entry point.  Multiple environments per entry point (or at the project level) will raise an error.

5. The 'use_conda' parameter applies to both environments (project level and entry point level).

6. The only way to specify an entry point environment is within a MLProject file.  

# Proposed code changes
1. [EntryPoint class in _project_spec.py](https://github.com/mlflow/mlflow/blob/88858b529bc1b49f37a4a3e7087649f85e62bf1a/mlflow/projects/_project_spec.py#L118) - add self.conda_env_path and self.docker_env instance variables, with None default values

2. [load_project() in _project_spec.py](https://github.com/mlflow/mlflow/blob/88858b529bc1b49f37a4a3e7087649f85e62bf1a/mlflow/projects/_project_spec.py#L27) - parse 'docker_env' and 'conda_env' from entry points and set according to Project level values if not specified.  Validate entry points using existing code within load_project.  May require refactoring existing code into isolated functions: validate_docker_env() and validate_conda_path().  Include the appropriate 'docker_env' and 'conda_env' values as arguments in call to EntryPoint(). 

3. [Project class in _project_spec.py](https://github.com/mlflow/mlflow/blob/88858b529bc1b49f37a4a3e7087649f85e62bf1a/mlflow/projects/_project_spec.py#L91) - modify get_entry_point() method, so that the returned entry point object has appropriate conda_env_path and docker_env variables set, taken from Project level setting if not specified at entry point level.  

4. [_run() in projects/__init__.py ](https://github.com/mlflow/mlflow/blob/88858b529bc1b49f37a4a3e7087649f85e62bf1a/mlflow/projects/__init__.py#L86) - set docker_env and conda_path from the entry point instead of the project
```python
project = load_project(work_dir)
entry_point_object = project.get_entry_point(entry_point)
docker_env = entry_point_object.docker_env
conda_env_path = entry_point.conda_env_path
```  
replace all references to 'project.docker_env' with 'docker_env' and all references to 'project.conda_path' with 'conda_env_path' 

5. [_validate_execution_environment() in projects/__init__.py ](https://github.com/mlflow/mlflow/blob/88858b529bc1b49f37a4a3e7087649f85e62bf1a/mlflow/projects/__init__.py#L507) - change input argument from 'project' to 'entry_point'.  Check 'entry_point.docker_env' instead of 'project.docker_env'.


# Proposed test changes
1. add a new entry point to [tests/resources/example_project](https://github.com/mlflow/mlflow/blob/7bccdaaa704efbb2d687e592e5de6a9809c16dbc/tests/resources/example_project/MLproject) - called 'entry_point_env' with appropriate syntax for an entry point level conda environment
2. add a new entry point to [tests/resources/example_docker_project](https://github.com/mlflow/mlflow/blob/7bccdaaa704efbb2d687e592e5de6a9809c16dbc/tests/resources/example_docker_project/MLproject) - called 'entry_point_env' with appropriate syntax for an entry point level docker environment
3. updates to existing tests and appropriate new tests, primarily in tests/projects/

# Proposed doc changes
A short note in the section [Specifying an Environment](https://github.com/mlflow/mlflow/blob/d92920018ce73a37ef1b716bd05f36a90dc0fd59/docs/source/projects.rst#specifying-an-environment), that the same top-level entries can be optionally specified within an entry point in order to customize the environment for a specific entry point.

# Potential downsides / complexities
This feature could increase the likelihood of incompatibilities between entry points.  For example, if two entry points use different versions of pandas, errors are likely to occur if one entry point tries to read an artifact generated by the other.  This risk can be reduced through good documentation and also keeping the project level environment specification as the preferred option.  Entry point level environments should be considered an advanced feature.

**Comment by jkthompson** [comment]
@mparkhe - would it be possible to get feedback on this proposed design?  If it goes in the right direction I could start working on this in the next few weeks.

**Comment by florianblume** [comment]
Any update on this? I'd be interested in this feature, too. And would be willing to help implement it :)

**Comment by jkthompson** [comment]
@florianblume  - I have not been working on this and don't have a lot of time to do so.  I'd be happy to provide feedback if you want to implement.  Would be good to get a blessing from the core devs before putting too much work into it though.

**Comment by abitrolly** [comment]
Why only conda/docker? Is it already possible to use different `requirements.txt` for each entrypoint?

**Comment by abitrolly** [comment]
I'd like to port GitLab's issue triager https://gitlab.com/gitlab-org/ml-ops/tanuki-stan/-/blob/master/.gitlab-ci.yml to MLflow. Training is quite expensive and requires node with GPU, but inference probably doesn't need such dependencies.

Ideally it should look like this.
```
name: tanuki-stan

entry_points:
  train:
    python_env: notebooks/requirements.tensorflow-gpu.txt
    parameters:
      # public|private
      data: string
    command: "cd notebooks; jupyter  --to script train_groups.ipynb; python classify_groups.py {data}"
  classify:
    python_env: scripts/requirements.txt
    parameters:
      issue: uri
      # yes|no
      comment: no
    command: "cd scripts; python3 classify_groups.py {issue} {comment}"
```
