### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hmcp22** [mlflow/mlflow#3063]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: WSL 2, Ubuntu 16.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.9.0
- **Python version**: 3.7.1

### Describe the problem
When running the docker example from mlflow/examples/docker in kubernetes it fails with the following error:
![image](https://user-images.githubusercontent.com/29867749/86822429-87cf9b00-c083-11ea-83e8-894659910b85.png)

Inspecting the logs I get this error message:
![image](https://user-images.githubusercontent.com/29867749/86822562-b2215880-c083-11ea-862e-47cfced357aa.png)

Having done some investigation, this seems to be due to the environment variable MLFLOW_RUN_ID being set at some point in the creation of the docker image from the base docker_env image. You can see this is the case by adding os.environ["MLFLOW_RUN_ID"] = ""  before the mlflow.start_run() line in the train.py file. Doing so completes the run without any issues as per the screenshot below:
![image](https://user-images.githubusercontent.com/29867749/86822075-10017080-c083-11ea-84b2-10e63002a1a5.png)

Note that I get the same error with the mlflow/python version specified in the original docker example and when I updated it to use the latest mlflow version (see Dockerfile attached).
[Dockerfile.txt](https://github.com/mlflow/mlflow/files/4886458/Dockerfile.txt)

I've looked through the code to try to figure out where this is happening and how to fix it but no success so far. I'm happy to submit a bug fix with some help from the mlflow community.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by Zangr** [comment]
cc @smurching @juntai-zheng

**Comment by MishaVeldhoen** [comment]
I'm having the same issue, and have also looked at the code briefly. It looks like the local mlflow generates a random run id here https://github.com/mlflow/mlflow/blob/939b494d9cccbb32999439fa744076f5fad28749/mlflow/store/tracking/file_store.py#L383, and then passes the ID along to kubernetes as an environment variable for the pod. The pod doesn't know about this run ID and throws the exception.

I also noticed that mlflow sets `MLFLOW_TRACKING_URI`  for the pod to the path where the code exists on the local machine. It ignores any tracking server that a user could have set in `kubernetes_job_template.yaml` (I guess in many cases the user would have set this to some remote/shared tracking server).

Applying the following job config directly does work (I'm running a tracking server and SFTP server in the same `mlflow` namespace):
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "mlflow-kubernetes-example-manual"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "mlflow-kubernetes-example-manual"
        image: "mlflow-kubernetes-example-manual"
        imagePullPolicy: Never  # When running on docker-desktop, don't pull
        command: ["python", "train.py", "--alpha=0.5", "--l1-ratio=0.1"]
        env:
        # Tracking server (service) running in the same namespace.
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server:5000"
        volumeMounts:
          # The following replaces the known_hosts file of the pod, and contains the keys
          # for the SFTP server.
        - name: known-hosts-volume
          mountPath: /root/.ssh/known_hosts
          subPath: known_hosts
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      volumes:
      - name: known-hosts-volume
        secret:
          secretName: known-hosts
```
