### ISSUE TITLE
[BUG] Database initialization fails if primary keys enforced

### ISSUE THREAD

**Issue by dpsommer** [mlflow/mlflow#3361]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **MLflow installed from (source or binary)**: Binary (pip)
- **MLflow version (run ``mlflow --version``)**: Latest (1.10.0)
- **Python version**: 3.7
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: `mlflow server` with a database backend store with primary keys enforced (see below)

### Describe the problem
MLflow server Alembic migrations fail silently if primary keys are enforced on the backend store database (e.g. via `--innodb-force-primary-key`). This is due to the migration dropping and re-creating the key as two separate steps.

### Code to reproduce issue
1. Download docker-compose version of bitnami MariaDB Galera image

`curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-mariadb-galera/master/docker-compose.yml > docker-compose.yml`

2. Create mlflow Dockerfile

```
FROM python:3.7-slim-buster

RUN apt update && apt install -y build-essential libmariadbclient-dev default-libmysqlclient-dev wait-for-it && \
  pip install --no-cache-dir mlflow boto3 mysqlclient

ENTRYPOINT wait-for-it -t 0 mariadb:3306 -- mlflow server --host=0.0.0.0 \
  --backend-store-uri mysql://root@mariadb:3306/mlflow \
  --default-artifact-root /tmp
```

3. Build mlflow docker container

`docker build . --tag mlflow`

4. Update docker-compose.yml to mlflow service

```
version: '2.1'

services:
  mariadb-galera:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    ports:
      - '3306:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mlflow
      - MARIADB_EXTRA_FLAGS=--innodb-force-primary-key
    networks: 
      - mlflow
  mlflow:
    image: 'mlflow:latest'
    depends_on:
      - mariadb-galera
    links:
      - "mariadb-galera:mariadb"
    networks: 
      - mlflow

networks:
  mlflow:
    driver: bridge

volumes:
  mariadb_galera_data:
    driver: local
```

5. Bring up containers

`docker-compose up -d`

6. MLflow fails silently

### Other info / logs

MLflow container logs:

```
wait-for-it: waiting for mariadb:3306 without a timeout
wait-for-it: mariadb:3306 is available after 9 seconds
2020/08/29 05:27:09 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2020/08/29 05:27:09 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
```

To view the exact error message (as it isn't captured in the container logs), run `alembic upgrade 451aebb31d03` from inside the MLflow container:

```
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py", line 28, in upgrade
    columns=['key', 'timestamp', 'step', 'run_uuid', 'value'])
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  ... (omitted for brevity)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 231, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1173, 'This table type requires a primary key')
[SQL: ALTER TABLE metrics DROP PRIMARY KEY ]
(Background on this error at: http://sqlalche.me/e/e3q8)​
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
