### ISSUE TITLE
[BUG] MLflow Projects: there is no --docker-args option in MLflow UI

### ISSUE THREAD

**Issue by TaikiInoue** [mlflow/mlflow#3383]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

<br>

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu18.04
- **MLflow installed from (source or binary)**: Binary (pip)
- **MLflow version (run ``mlflow --version``)**: 1.10.0
- **Python version**: 3.6.5
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: `mlflow run --docker-args runtime=nvidia https://github.com/TaikiInoue/MLProjects.git#SSAD`

<br>

### Describe the problem
My mlflow run command `mlflow run --docker-args runtime=nvidia https://github.com/TaikiInoue/MLProjects.git#SSAD` works correctly. However, there is no `--docker-args` option in MLflow UI 

<br>

### Code to reproduce issue
This is my MLproject file
```
name: ssad

docker_env:
    image: ssad:latest
    environment: ["MLFLOW_TRACKING_URI", "DATABRICKS_HOST", "DATABRICKS_TOKEN", "AZURE_STORAGE_CONNECTION_STRING"]

entry_points:
    main:
        parameters:
            data_repo: {type: str, default: "https://github.com/TaikiInoue/DVC.git"}
            data_commid_hash: {type: str, default: "a6e3c2288e7808162d46d9f998eb7c674ad90384"}
            code_repo: {type: str, default: "https://github.com/TaikiInoue/SSAD.git"}
            code_commit_hash: {type: str, default: "18013875df1da233f25bf38d8751d100033a4cda"}
        command: "sh entry_points.sh --data_repo={data_repo} --data_commid_hash={data_commid_hash} --code_repo={code_repo} --code_commit_hash={code_commit_hash}"
```

<br>

`runtime=nvidia` was specified to train my model with GPU, and this command works correctly.
```
mlflow run --docker-args runtime=nvidia https://github.com/TaikiInoue/MLProjects.git#SSAD
```

<br>

This is my MLflow UI. As you can see, there is no `--docker-args` option, and I can't reproduce the experiment with this command. Of course, it works correctly when I add `--docker-args` option manually.

![image](https://user-images.githubusercontent.com/29189728/92127974-db205880-ee3c-11ea-93a7-5361904bd011.png)

<br>

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
