### ISSUE TITLE
[BUG] MLflow not picking up environment variables and not mounting volumes when run with --backend kubernetes

### ISSUE THREAD

**Issue by soma-upday** [mlflow/mlflow#3448]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.5 (18F203)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: Python 3.8.5
- **npm version, if running the dev UI**: Not using UI
- **Exact command to reproduce**: `MLFLOW_TRACKING_URI=https://xxxx.xxxxx.com MLFLOW_TRACKING_USERNAME=xxxx MLFLOW_TRACKING_PASSWORD=xxxxx mlflow run -P alpha=0.5  . --backend kubernetes --backend-config kubernetes_config.json --experiment-name test1`

### Describe the problem
**MLflow not picking up environment variables when run with --backend kubernetes**

I'm trying to get MLProject to run inside Kubernetes following this https://github.com/mlflow/mlflow/tree/master/examples/docker with the below command

The describe pod however only show MLFLOW_TRACKING_URI being picked up not the other two env variables, see below

```
Name:         tutorial-2020-09-22-11-17-54-381954-mgptt
Namespace:    mlflow
Priority:     0
Node:         kind-worker/172.19.0.3
Containers:
  tutorial:
    Container ID:  containerd://7de7124f96ea83da474e66bc7b2119cba4d4e0ab7188e135e3ed190dde5c8df4
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 22 Sep 2020 11:17:55 +0200
      Finished:     Tue, 22 Sep 2020 11:17:56 +0200
    Ready:          False
    Restart Count:  0
    ...
    Environment:
      MLFLOW_RUN_ID:         1a83aa6a16704883a775ad50bc94c7e9
      MLFLOW_TRACKING_URI:   https://xxxx.xxxxx.com
      MLFLOW_EXPERIMENT_ID:  73
    ...
```

The env variables are described in the MLproject file as below, to note the volume mentioned below also is also not mounted as expected

```
docker_env:
  image: somaupday/mlflow-sklearn:latest
  environment: [["MLFLOW_TRACKING_URI", "https://xxxx.xxxxx.com"], ["MLFLOW_TRACKING_USERNAME", "mlflow"], ["MLFLOW_TRACKING_PASSWORD", "xxxxxxx"]]
  volumes: ["${HOME}/.aws:/root/.aws"]
```

other relevant files for reference 
**kubernetes_config.json**
```
{
  "kube-context": "kind-kind",
  "repository-uri": "xxxxx/mlflow-sklearn",
  "kube-job-template-path": "./kubernetes_job_template.yaml"
}
```

**kubernetes_job_template.yaml**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{replaced with MLflow Project name}"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "{replaced with MLflow Project name}"
        image: "{replaced with URI of Docker image created during Project execution}"
        command: ["{replaced with MLflow Project entry point command}"]
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      restartPolicy: Never
```

Additionally I also don't see the volumes are not mounted as expected.. 

PS: This is based on one of the MLproject that already runs in docker for us, we just want to run it in Kubernetes instead

### Code to reproduce issue
```
MLFLOW_TRACKING_URI=https://xxxx.xxxxx.com MLFLOW_TRACKING_USERNAME=xxxx MLFLOW_TRACKING_PASSWORD=xxxxx mlflow run -P alpha=0.5  . --backend kubernetes --backend-config kubernetes_config.json --experiment-name test1
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
