### ISSUE TITLE
[BUG] mlflow server does not work behind ingress proxy (kubernetes, traefik)

### ISSUE THREAD

**Issue by dingobar** [mlflow/mlflow#3530]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian/Ubuntu/CentOS
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: latest
- **Python version**: 3.8
- **npm version, if running the dev UI**: na
- **Exact command to reproduce**: mlflow server [args]

### Describe the problem
When running in a container behind a proxy, for example in a kubernetes cluster with a traefik or nginx ingress in front, flask (actually its dependency werkzeug) does not handle forwarded request headers correctly.

The issue is explained in detail in the [werkzeug docs](https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#module-werkzeug.middleware.proxy_fix).

### Code to reproduce issue
An ingress resource in kubernetes can contain a host and a URL prefix like this:
```yaml
...
    - host: mlflow.my.domain.here.com
      http:
        paths:
        - backend:
            serviceName: mlflow
            servicePort: 80
          path: /mlops/mlflow
...
```
When deployed with an mlflow deployment and a service in front, I would expect to hit the server in the browser with `https://mlflow.my.domain.here.com/mlops/mlflow`. However, the werkzeug WSGI does not translate the forwarded headers in the request correctly and thus the request never reaches the app itself.

If anyone is interested, the dockerfile for the container looks like this:
```Dockerfile
FROM python:3.8.2-slim

RUN pip install PyMySQL==0.9.3 && \   
    pip install psycopg2-binary==2.8.5 && \
    pip install mlflow[extras]==1.9.1

ENTRYPOINT ["mlflow", "server"]
```

And the server is run like this in the kubernetes deployment:
```yaml
...
        containers:
        - args:
          - --port=80
          - --host=0.0.0.0
          - --backend-store-uri=postgresql://mlflow:my-password@my-postgres-database:5432/mlflow
          - --default-artifact-root=s3://my-bucket-here
          - --gunicorn-opts=--log-level debug
          - --static-prefix=/mlops/mlflow
...
```

### Other info / logs
I've made a PR on this to illustrate how to solve it, but I will need some help writing proper tests for it and also running the test suite that already exists.

Web-servers is admittedly not my strongest craft so please excuse my simple minded explanation of the issue.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
