### ISSUE TITLE
mlflow cli overrides experiment-id 

### ISSUE THREAD

**Issue by kyrre** [mlflow/mlflow#355]
The mlflow cli overrides whatever experiment-id you pass to the mlflow.start_run method. 

The minimal example below demonstrates the problem. In practice this means that it is not possible to let the user specify experiment-name and then set the associated experiment_id.

mlflow==0.5

main.py:
```
import click
import mlflow


@click.command()
@click.option("--experiment-id", required=True, type=int)
def main(experiment_id):
    with mlflow.start_run(experiment_id=experiment_id):
        pass


if __name__ == '__main__':
    main()

```

MLproject
```
name: dga

conda_env: model.yaml

entry_points:
  main:
    parameters:
      experiment-id: int

    command: "python main.py --experiment-id={experiment-id}"
```

model.yaml:
```
name: error
channels:
  - defaults
dependencies:
  - python=3.6
  - click
  - pip:
    - mlflow
```
