### ISSUE TITLE
[BUG] - UI breaks when there is space in input fields names

### ISSUE THREAD

**Issue by andreoliveira-creditas** [mlflow/mlflow#3596]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [X] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.10
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: 3.7.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 
```
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

from mlflow.models.signature import infer_signature
import mlflow

iris = load_iris()
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                               columns= iris['feature_names'] + ['target'])

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.3)
clf = LogisticRegression(multi_class='multinomial')
clf.fit(X_train, y_train)
mlflow.sklearn.log_model(clf, 'logistic_regression', signature=infer_signature(X_train, clf.predict(X_train)))
```

### Describe the problem
I am running Mlflow server on a docker container using a Postgres database as backend-store and a s3 bucket to store artifacts and I am trying to run an example from MLflow documentation using the iris dataset from scikit-learn.
When i run an experiment everything works perfectly, i can see the results in the UI and also the metadata in Postgre and artifacts in S3. But when i register a model and try to see the model version page in UI (#/models/my-model/versions/1) i get the "Something went wrong. If this error persists, please report an issue here." error.

When i look at server log i found no error logged, and inspecting the page there is the following error: 
```
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 72 of the JSON data
    _t reducers.js:140
    Bs ModelVersionPage.js:228
```
that refers to: schemaMap['inputs'] = JSON.parse(artifact.signature.inputs);

As i am using the iris dataset and its fields names contains spaces, i tried to remove the spaces from the fields and then everything works perfectly!. But as i am following the example from documentation i got confused, is it a bug? is it expected to break UI when there is space in model inputs fields?
Here is the part of documentation i am following: https://mlflow.org/docs/latest/models.html#how-to-log-models-with-signatures

### Code to reproduce issue

my Dockerfile that runs mlflow server:
```
FROM python:3.7-slim-buster

RUN mkdir /home/app/
WORKDIR /home/app

RUN apt-get update \
    && apt-get install -y gunicorn3 jq npm wget curl git libgomp1 postgresql python-psycopg2 libpq-dev

RUN pip install mlflow == 1.11.0 \
                         pandas == 1.1.3 \
                         numpy == 1.19.0 \
                         scikit-learn == 0.23.0 \
                         matplotlib == 3.3.2 \
                         psycopg2-binary \
                         boto3
COPY ./ /home/app
ENTRYPOINT ["sh", "init.sh"]
```
init.sh:
```
mlflow server \
    --backend-store-uri $DATABASE_URL \
    --default-artifact-root "s3://my-bucket/mlflow/artifacts/" \
    --gunicorn-opts "--log-level debug" \
    --host 0.0.0.0
```
tracking example:
```
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

from mlflow.models.signature import infer_signature
import mlflow

iris = load_iris()
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                               columns= iris['feature_names'] + ['target'])

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.3)
clf = LogisticRegression(multi_class='multinomial')
clf.fit(X_train, y_train)
mlflow.sklearn.log_model(clf, 'logistic_regression', signature=infer_signature(X_train, clf.predict(X_train)))
```

### Other info / logs
```
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 72 of the JSON data
    _t reducers.js:140
    Bs ModelVersionPage.js:228
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@andreoliveira-creditas Thanks for reporting this issue. I was able to reproduce the issue and found the root cause.

https://github.com/mlflow/mlflow/blob/a902588ad7c9eaa4751ca7202a0a6fc66348887d/mlflow/models/model.py#L93

`yaml.safe_dump` split a long field into multiple lines.

```yaml
artifact_path: logistic_regression
flavors:
  python_function:
    env: conda.yaml
    loader_module: mlflow.sklearn
    model_path: model.pkl
    python_version: 3.6.10
  sklearn:
    pickled_model: model.pkl
    serialization_format: cloudpickle
    sklearn_version: 0.23.2
run_id: 1dd52e00d10b4cb3a6a398c91258912d
signature:
  inputs: '[{"name": "sepal length (cm)", "type": "double"}, {"name": "sepal width  # 🔥 line break inserted here
    (cm)", "type": "double"}, {"name": "petal length (cm)", "type": "double"}, {"name":
    "petal width (cm)", "type": "double"}]'
  outputs: '[{"type": "double"}]'
utc_time_created: '2020-10-26 15:15:08.838202'
```

**Comment by harupy** [comment]
A quick fix that I found is specify `width`

```python
return yaml.safe_dump(..., width=10000)
```

output:

```
artifact_path: logistic_regression
flavors:
  python_function:
    env: conda.yaml
    loader_module: mlflow.sklearn
    model_path: model.pkl
    python_version: 3.6.10
  sklearn:
    pickled_model: model.pkl
    serialization_format: cloudpickle
    sklearn_version: 0.23.2
run_id: 37b285d713cc4edf8e6eb883b040936d
signature:
  inputs: '[{"name": "sepal length (cm)", "type": "double"}, {"name": "sepal width (cm)", "type": "double"}, {"name": "petal length (cm)", "type": "double"}, {"name": "petal width (cm)", "type": "double"}]'
  outputs: '[{"type": "double"}]'
utc_time_created: '2020-10-26 15:35:42.608045'
```
