### ISSUE TITLE
[FR] Global parameters for projects

### ISSUE THREAD

**Issue by lorenzwalthert** [mlflow/mlflow#3672]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

I can contribute the R part, ideally someone else implements this for the other language clients.

## Proposal Summary

I suggest to allow specifying parameters in MLprojects globally in addition to per entry-point to allow code duplication reduction.

## Motivation

I am using MLflow in my daily workflows and I came across the following problem: MLprojects can grow big in terms of entry points and parameters. Some entry points share parameters, e.g. how to treat missing values. It would be great if these could be defined globally in MLproject instead of by entry point because this would reduce duplication and cognitive burden for the user.In particular if a user wants to change the value of the parameter, it has to be updated in multiple places, which is error prone. Building on the [example](https://mlflow.org/docs/latest/projects.html#mlproject-file) from the doc, here is how I imagine this to be implemented:

```yaml
name: My Project
parameters: # <- This is a new key
  on_missing: {type: string, default: "error"}


conda_env: my_env.yaml
# Can have a docker_env instead of a conda_env, e.g.
# docker_env:
#    image:  mlflow-docker-example

entry_points:
  main:
    parameters:
       regularization: {type: float, default: 0.1}
  command: "python train.py -r {regularization} --on_missing={on_missing}
  validate:
    parameters:
      data_file: path
    command: "python validate.py {data_file} --on_missing={on_missing}"
```

I suggest that the parameters defined in an entry point take precedence over the ones defined globally in case both are defined. This is a non-breaking API change and would benefit everyone who uses MLprojects with entry points that share at least one parameter. I think the benefit of this relative to the implementation effort is small.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)
