### ISSUE TITLE
[BUG] Unable to list artifacts stored under sqlite:/mlflow.db/2/....../artifacts

### ISSUE THREAD

**Issue by raphaelauv** [mlflow/mlflow#3764]
With the simple example of the documentation I have an error

**Unable to list artifacts stored undersqlite:/mlflow.db/2/a5e6dc8542ca403e8c2609d63779e273/artifacts for the current run.** 

This is my configuration :

mlflow_dockerfile ->
```yaml
FROM python:3.7-slim-buster
RUN pip install mlflow
RUN pip install psycopg2-binary
RUN mkdir -p /opt/mlflow
WORKDIR /opt/mlflow
```

```yaml
version: '3.8'

services:
  mlflow-db:
    image: postgres:13.1
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432
  web:
    build:
      context: ./src/dockerfiles/mlflow/
      dockerfile: Dockerfile
    container_name: mlflow_server
    ports:
      - 5000:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql+psycopg2://mlflow:password@mlflow-db:5432/mlflowdb --default-artifact-root /opt/mlflow
```
```python
import os
from random import random, randint
from mlflow import log_metric, log_param, log_artifacts

import mlflow as ml

ml.set_tracking_uri("http://localhost:5000")
ml.set_experiment("my-experiment")

if __name__ == "__main__":
    # Log a parameter (key-value pair)
    log_param("param1", randint(0, 100))

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", random())
    log_metric("foo", random() + 1)
    log_metric("foo", random() + 2)

    # Log an artifact (output file)
    if not os.path.exists("outputs"):
        os.makedirs("outputs")
    with open("outputs/test.txt", "w") as f:
        f.write("hello world!")
    log_artifacts("outputs")

```

This python scritpt give 

```
    raise MlflowException(
mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: sqlite:/mlflow.db/2/a5e6dc8542ca403e8c2609d63779e273/artifacts. Currently registered schemes are: ['', 'file', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs', 'hdfs', 'viewfs', 'runs', 'models']

```

And inside the UI of MLflow server

```
Unable to list artifacts stored undersqlite:/mlflow.db/2/a5e6dc8542ca403e8c2609d63779e273/artifacts for the current run. P
```

Do you have any idee ? Thank you

![Screenshot from 2020-12-02 16-47-44](https://user-images.githubusercontent.com/10202690/100905692-a6b64a00-34c8-11eb-907c-9278642cf704.png)
