### ISSUE TITLE
Mlflow file - read from config

### ISSUE THREAD

**Issue by Adblu** [mlflow/mlflow#3959]
Here is my mlproject file:

```
name: project
entry_points:

  load:
    command: "do some stuff"

  train:
    command: "python -m torch.distributed.launch --nproc_per_node=GPU_NUMBER train.py"

  main:
    command: "do some stuff"
```

I have a config file when I have specified the number of GPUS, and I dont want to specify it in mlproject file.
Is there a possibility that mlproject file can read it from config.py file somehow ?

config.py:
```
GPU_NUMBER: 8
```

I can only use command:
```
mlflow run project
```
