### ISSUE TITLE
Examples are not working on Windows

### ISSUE THREAD

**Issue by adalsteinnpals** [mlflow/mlflow#4020]
The formatting of the MLproject files are not compatible with Windows.

E.g. for the lightgbm example 

```
name: lightgbm-example
conda_env: conda.yaml
entry_points:
  main:
    parameters:
      learning_rate: {type: float, default: 0.1}
      colsample_bytree: {type: float, default: 1.0}
      subsample: {type: float, default: 1.0}
    command: |
        python train.py \
          --learning-rate={learning_rate} \
          --colsample-bytree={colsample_bytree} \
          --subsample={subsample}
```

Results in the error

```
2021/01/25 09:25:00 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-90be7b5d78a130baa4adba24e7e5c5ddbe09d4c4 && python train.py \
  --learning-rate=0.2 \
  --colsample-bytree=0.8 \
  --subsample=0.9
' in run with ID '251f09fa09494b6582326227b1e8e7ae' ===
usage: train.py [-h] [--learning-rate LEARNING_RATE]
                [--colsample-bytree COLSAMPLE_BYTREE] [--subsample SUBSAMPLE]
train.py: error: unrecognized arguments: \
2021/01/25 09:25:08 ERROR mlflow.cli: === Run (ID '251f09fa09494b6582326227b1e8e7ae') failed ===
```

Reformatting and removing backslashes solves this issue:

```
name: lightgbm-example
conda_env: conda.yaml
entry_points:
  main:
    parameters:
      learning_rate: {type: float, default: 0.1}
      colsample_bytree: {type: float, default: 1.0}
      subsample: {type: float, default: 1.0}
    command: |
        python train.py  --learning-rate={learning_rate} --colsample-bytree={colsample_bytree}  --subsample={subsample}
```
