### ISSUE TITLE
[BUG] Artifacts are there but not shown in UI

### ISSUE THREAD

**Issue by NicolasWinckler** [mlflow/mlflow#4654]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:-
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker image: nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**:1.19.0
- **Python version**: 3.6.9
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: cd path/that/contain/mlruns  and mlflow ui -h 0.0.0.0 -p 5000

### Describe the problem

Hi I am not sure what am i doing wrong, but everything seems to work except that artifacts are not seen by the UI although they are in the artifact directory. Parameters and metrics are correctly shown.

### Code to reproduce issue
Below is the minimal code to reproduce my issue

`
import mlflow
import yaml
def main():
    with open(config_file, 'r') as cfile:
         yml = yaml.load(cfile, Loader=yaml.FullLoader)
     # copy config files
    mlflow.log_dict(yml, "config.yaml")
    mlflow.log_artifact(yml['model-config-file'])

if __name__ == '__main__':
    mlflow.set_tracking_uri("/out/mlruns")
    mlflow.set_experiment("dummy-test") 
    
    with mlflow.start_run():
        main()
`

Then, to launch the UI, I go to the parent directory of mlruns and run `mlflow ui -h 0.0.0.0 -p 5000`
` tree mlruns/
mlruns/
├── ...
└── 1
    ├── 3822fcba86334cf08754bf5baf37a36a
    │   ├── artifacts
    │   │   ├── config.yaml
    │   │   └── model.yaml
    │   ├── meta.yaml
    │   ├── metrics
    │   ├── params
    │   └── tags
    │       ├── mlflow.source.name
    │       ├── mlflow.source.type
    │       └── mlflow.user
    └── meta.yaml
mlflow ui -h 0.0.0.0 -p 5000
`

### Other info / logs

In my complete code I also log the model and tensorboard data into a directory with mlflow.log_artifacts(log_path, artifact_path="tf_logs"). Data are correctly copied in the artifact directory but are not seen either.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by apurva-koti** [comment]
Hi @NicolasWinckler , I'm not able to reproduce this by copying your code and making minimal modifications (since I don't have `config_file`). Are you sure `model-config-file` contains a valid file location, and that the YAML file is generally valid?

**Comment by NicolasWinckler** [comment]
Hi @apurva-koti , I am sorry, I haven't seen your reply up to now. The YAML files are at least correctly copied into the artifacts directory. Below is a model config example:
``` yaml
pre_train_path: 
max-epochs: 100
reg-factor:  0.0 
class-nb:  6269
learning-rate-vals: [0.0001, 0.00005, 0.000001] 
learning-rate-schedule: [160000, 320000] 
``` 
I don't know if it plays a role, but maybe more details on my environment may help:
I am using an ubuntu inside a virtual box, in which i do double ssh forwarding to get the mlflow dashboard on google chrome. The mlflow server is launch from a docker on a remote machine. I can see correctly metrics, parameters, and tags but not artifacts from the dashboard. 

In other projects I could see the artifacts very well and doing the same kind of things. The main difference was an earlier mlflow version, a docker based on [deepo ](https://hub.docker.com/r/ufoym/deepo) and another remote machine with only one ssh forwarding.

**Comment by emv-dev** [comment]
I have this issue today, 4 years later.

```python
import mlflow
from lightning.pytorch.cli import LightningArgumentParser, LightningCLI

import src.data  # noqa: F401
import src.models
from src.utils import assert_committed

if __name__ == "__main__":
    git_hash = assert_committed(False)
    mlflow.set_tracking_uri('http://localhost:5000') #required to log artifacts. -> mlartifacts folder
    mlflow.set_tag("git_commit", git_hash)
    mlflow.log_artifact("config.yaml", artifact_path="config")
    LightningCLI(
        parser_kwargs={"parser_mode": "omegaconf"},
        # save_config_kwargs={"config_filename": f"config_{run_id}_{git_hash[:9]}.yaml"},
        save_config_kwargs={"overwrite": True},
    )
```

config.yaml is in ./, it is copied to ./mlartifacts/.../config/config.yaml but does not show in the UI. I still dont see config.yaml in experiments > test >overjoyed-slug-911 > artifacts tab. i only see the model artifacts.

```yaml
# lightning.pytorch==2.5.5
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: 
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: test
      run_name: null
      tracking_uri: null
      tags: null
      save_dir: ./mlruns
      log_model: all
      checkpoint_path_prefix: ''
      prefix: ''
      artifact_location: null
      run_id: null
      synchronous: false
  callbacks: 
    - class_path: src.optim.autoscheduler.AutomaticLRCallback
      init_args:
        alpha: 1.01
        check_interval: 20
        min_lr: 1e-8
        max_lr: 1e0
  fast_dev_run: false
  max_epochs: 5
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 1
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
data:
  class_path: src.data.CollatedReachDataModule
  init_args:
    reach: 4
    batch_size: 16
    split_ratios:
    - 0.7
    - 0.2
    - 0.1
    collate_len: 1
    collate_skip: 1
    num_workers: 0
    pin_memory: false
    persistent_workers: false
    shuffle: true
model:
  class_path: src.models.ShoalingCNN
  init_args:
    shape:
    - ${data.init_args.collate_len}
    - 1592
    - 782
    loss_fn: 
      class_path: torch.nn.BCEWithLogitsLoss
optimizer: Adam
lr_scheduler: null
ckpt_path: null
```
