### ISSUE TITLE
[BUG] MLFlow - NGINX - Docker

### ISSUE THREAD

**Issue by pejmanS21** [mlflow/mlflow#6187]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

So, I want to use mlflow with Nginx in a specific endpoint (like `http://<ip-address>/mlflow`). I'm using reverse_proxy to do so. But after executing via docker-compose, mlflow doesn't load correctly. 
Dockerfile contains simple copy and installing requirements.

Here is my **nginx.conf**

```
http {
    server {
        listen 80;
        server_name _;
        access_log /var/log/nginx/access.log combined;
        error_log /var/log/nginx/error.log debug;
        location =/mlflow {
            proxy_pass http://mlflow:5000/;
        }
        location / {
            return 200 "OK";
        }
    }
}
```

and `docker-compose.yml`

```
services:
  mlflow:
    image: mlflow
    build: ./mlflow-image
    container_name: mlflow-backend
    domainname: mlflow
    restart: always
    ports:
      - 5000:5000
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "5000"
  nginx:
    image: nginx
    build: ./nginx
    container_name: mlflow-nginx
    domainname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mlflow

```
<img width="1260" alt="Screen Shot 2022-07-04 at 3 31 24 PM" src="https://user-images.githubusercontent.com/73995528/177146210-7c4ffdac-47b8-4660-8220-2103b97ee9a3.png">

### Code to reproduce issue

```
http {
    server {
        listen 80;
        server_name _;
        access_log /var/log/nginx/access.log combined;
        error_log /var/log/nginx/error.log debug;
        location =/mlflow {
            proxy_pass http://mlflow:5000/;
        }
        location / {
            return 200 "OK";
        }
    }
}
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
