### ISSUE TITLE
[SETUP-BUG] dockerized local setup: Artifacts not showing in MLflow UI

### ISSUE THREAD

**Issue by helpsystems-mushkevych** [mlflow/mlflow#6942]
### System information

- **OS Platform and Distribution**:  Docker `python:3.9` image

- **MLflow installed from (source or binary)**: `pip`
- **MLflow version (run ``mlflow --version``)**: `1.29.0`
- **Python version**: `3.9`

### Code to reproduce issue

`mlflow.dockerfile`:
```Dockerfile
FROM python:3.9

WORKDIR /app

RUN pip install \
    mlflow \
    psycopg2

RUN mkdir /mlflow/ && \
    mkdir --parents /data/artifacts/ && \
    chmod 777 /data/artifacts
```

`docker-compose.yaml`:
```yaml
version: "3.8"

networks:
  mlflow-network:
    driver: bridge

services:
  mlflow-artifacts:
    container_name: mlflow-artifacts

    build:
      context: .
      dockerfile: mlflow.dockerfile
    expose:
      - "5500"
    volumes:
      # /HOST:/CONTAINER
      - "./data/mlflow/artifacts:/data/artifacts"
    ports:
      # HOST:CONTAINER
      - "0.0.0.0:5500:5500"
    networks:
      - mlflow-network
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5500
      --artifacts-destination /data/artifacts
      --serve-artifacts
      --artifacts-only
      --gunicorn-opts "--log-level debug"

  mlflow-db:
    container_name: mlflow-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow
    networks:
      - mlflow-network
    volumes:
      # /HOST:/CONTAINER
      - "./data/mlflow/db:/var/lib/postgresql/data"
    restart: always

  mlflow-tracking:
    container_name: mlflow-tracking

    build:
      context: .
      dockerfile: mlflow.dockerfile
    expose:
      - "5000"
    ports:
      # HOST:CONTAINER
      - "0.0.0.0:5000:5000"
    networks:
      - mlflow-network
    restart: "unless-stopped"
    depends_on:
      - mlflow-db
      - mlflow-artifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://postgres:postgres@mlflow-db:5432/mlflow
      --default-artifact-root http://0.0.0.0:5500/api/2.0/mlflow-artifacts/artifacts/experiments
      --gunicorn-opts "--log-level debug"

volumes:
  mlflow-db:
    driver: local
  mlflow-artifacts:
    driver: local
```

### start-up command
```shell
 docker-compose --file mlflow.docker-compose.yaml up --detach
```

### Describe the problem

The goal is to have an MlFlow running locally in `production-like` configuration. For that I have followed the guide https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts but faced an issue that the Artifacts are not showing in the UI.
I.e: the artifacts folder in the filesystem is populated, but the UI is not loading.

Please advise.

**Comment by dbczumar** [comment]
Hi @helpsystems-mushkevych , can you try adding the `hostname` configuration to your `mlflow-artifacts` service definition and then changing  `--default-artifact-root http://0.0.0.0:5500/api/2.0/mlflow-artifacts/artifacts/experiments` to `--default-artifact-root http://<your_host_name>:5500/api/2.0/mlflow-artifacts/artifacts/experiments` ? I suspect that 0.0.0.0 might not be the right hostname. You may also have success with --default-artifact-root http://127.0.0.1:5500/api/2.0/mlflow-artifacts/artifacts/experiments.

**Comment by helpsystems-mushkevych** [comment]
@dbczumar  thanks. I have simplified the setup a bit

`mlflow.dockerfile` : 
```Dockerfile
FROM python:3.9

RUN pip install \
    mlflow \
    psycopg2 \
    gunicorn[gthread]

RUN mkdir /mlflow/ && \
    mkdir --parents /data/artifacts/ && \
    chmod 777 /data/artifacts
```

`docker-compose.yaml` : 
```yaml
version: "3.8"

networks:
  mlflow-network:
    driver: bridge

services:
  mlflow-db:
    container_name: mlflow-db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow
    networks:
      - mlflow-network
    volumes:
      # /HOST:/CONTAINER
      - "./data/mlflow/db:/var/lib/postgresql/data"
    restart: always

  mlflow-server:
    container_name: mlflow-server
    image: mlflow-server:latest

    build:
      context: .
      dockerfile: mlflow.dockerfile
    expose:
      - "5000"
    ports:
      # HOST:CONTAINER
      - "0.0.0.0:5000:5000"
    networks:
      - mlflow-network
    restart: "unless-stopped"
    volumes:
      # /HOST:/CONTAINER
      - "./data/mlflow/artifacts:/data/artifacts"
    depends_on:
      - mlflow-db
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --artifacts-destination /data/artifacts
      --backend-store-uri postgresql://postgres:postgres@mlflow-db:5432/mlflow
      --gunicorn-opts "--timeout 180 --log-level debug --access-logfile -"

volumes:
  mlflow-db:
    driver: local
  mlflow-server:
    driver: local
```
