### ISSUE TITLE
[BUG] SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by Rusteam** [mlflow/mlflow#6987]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker on MacOS M1 Monterey
- **Python version**: 3.10

### Describe the problem

Launching mlflow tracking server with postgres database causes this issue. However, when I simply connect to the database with psql, I do not see any issues.

### Code to reproduce issue

Dockerfile:

```
FROM python:3.10-bullseye

RUN pip install --no-cache mlflow~=1.29.0 psycopg2-binary~=2.9.3

CMD mlflow server \
      --host 0.0.0.0 \
      --port 5000 \
      --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/mlflow \
      --default-artifact-root ${DEFAULT_ARTIFACT_ROOT}
```

docker-compose.yml
```
services:
  mlflow:
    build: .
    image: finegrained/mlflow:0.1
    container_name: fg-mlflow
    restart: always
    ports:
      - 5100:5000
    environment:
      PG_HOST: mlflow_db
      PG_USER: ${MLFLOW_POSTGRES_USER:?err}
      PG_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD:?err}
      DEFAULT_ARTIFACT_ROOT: ${MLFLOW_DEFAULT_ARTIFACT_ROOT:?err}
    depends_on:
      - mlflow_db

  mlflow_db:
    image: postgres:14-bullseye
    container_name: fg-mlflow-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
```

.env example:
```
MLFLOW_DEFAULT_ARTIFACT_ROOT=./mlruns
POSTGRES_PASSWORD=postgres
MLFLOW_POSTGRES_USER=mlflow
MLFLOW_POSTGRES_PASSWORD=mlflow
```

### Stack trace

```
fg-mlflow    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
fg-mlflow    | Operation will be retried in 1.5 seconds
fg-mlflow    | 2022/10/06 03:49:37 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
fg-mlflow    | (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
