### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by shervin64** [mlflow/mlflow#739]
In the docs there is an example project referenced on this page:

https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html

(1) Where can we find this example:

```>>> tree example/sklearn_iris/mlruns/run1/outputs/linear-lr```

(2) Is there any documentation on what the ``main`` values does?

```
python_function:
  code: code
  data: data/model.pkl
  loader_module: mlflow.sklearn
  env: mlflow_env.yml
  main: sklearn_iris
```
