### ISSUE TITLE
[BUG] MLflow Tracking server with proxied artifact access fails with `ValueError: not enough values to unpack (expected 2, got 1)`

### ISSUE THREAD

**Issue by TomSteenbergen** [mlflow/mlflow#7481]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 12.6
- **Python version**: 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

Both on Kubernetes and locally using `docker compose`, I cannot get the proxied artifact access to work with MLflow Tracking. I've followed the docs and consulted other issues and threads, but have not been able to solve it.

Below, I attached the `docker-compose.yml` to spin up a MLflow Tracking Server locally with a Postgres database and Minio S3 storage. I checked and I correctly set all the required environment variables when running the `mlflow server` command. 

What's missing in my solution?

#### Client information:
```
# MLflow < 2.0
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

# MLflow >= 2.0
mlflow.doctor()
```

```
MLflow version: 2.0.1
Tracking URI: http://127.0.0.1:5001
Artifact URI: mlflow-artifacts:/9/3d05766953f247d8ac1cf2bad8126bd8/artifacts
System information: Darwin Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
Python version: 3.10.7
MLflow version: 2.0.1
MLflow module location: <redacted>/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: http://127.0.0.1:5001
Registry URI: http://127.0.0.1:5001
Active experiment ID: 9
Active run ID: 3d05766953f247d8ac1cf2bad8126bd8
Active run artifact URI: mlflow-artifacts:/9/3d05766953f247d8ac1cf2bad8126bd8/artifacts
MLflow environment variables: {}
MLflow dependencies: {
    "click": "8.1.3",
    "cloudpickle": "2.2.0",
    "databricks-cli": "0.17.3",
    "entrypoints": "0.4",
    "gitpython": "3.1.29",
    "pyyaml": "6.0",
    "protobuf": "4.21.10",
    "pytz": "2022.6",
    "requests": "2.28.1",
    "packaging": "21.3",
    "importlib-metadata": "5.1.0",
    "sqlparse": "0.4.3",
    "alembic": "1.8.1",
    "docker": "6.0.1",
    "Flask": "2.2.2",
    "numpy": "1.23.5",
    "scipy": "1.9.3",
    "pandas": "1.5.2",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.41",
    "scikit-learn": "1.1.3",
    "pyarrow": "10.0.1",
    "shap": "0.41.0",
    "markdown": "3.4.1",
    "matplotlib": "3.6.2",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}
```

#### Server command
```
mlflow server \
--backend-store-uri "$MLFLOW_BACKEND_STORE_URI" \
--artifacts-destination "$MLFLOW_ARTIFACTS_DESTINATION" \
--serve-artifacts \
--host 0.0.0.0 \
--port 5001
```

#### Docker-compose file:
```
---
version: "3"
services:
  minio:
    restart: always
    image: minio/minio
    container_name: mlflow_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    entrypoint: sh
    command: -c 'mkdir -p /data/local-test-mlflow-tracking && minio server /data --console-address ":9001" --address ":9000"'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ~/mlflow_minio_data:/data
  db:
    restart: always
    image: postgres:alpine
    container_name: mlflow_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ~/mlflow_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mlflow_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
  app:
    restart: always
    build:
      context: .
      args:
        - NEXUS_USERNAME=${NEXUS_USERNAME}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - db
      - minio
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      - MLFLOW_ARTIFACTS_DESTINATION=http://127.0.0.1:9000/local-test-mlflow-tracking/mlartifacts/
      - MLFLOW_BACKEND_STORE_URI=postgresql://postgres:test@db:5432/mlflow_db
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123

networks:
  backend:
    driver: bridge

volumes:
  mlflow_postgres_data: null
  mlflow_minio_data: null
```

### Code to reproduce issue

```python
from pathlib import Path
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5001")
mlflow.set_experiment("some-new-experiment")
with mlflow.start_run():
    mlflow.log_artifact(Path(__file__))
```

### Stack trace

```python
Traceback (most recent call last):
  File "<redacted>/mlflow_test.py", line 7, in <module>
    mlflow.log_artifact(Path(__file__))
  File "<redacted>/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 778, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "<redacted>/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1002, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "<redacted>/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 416, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "<redacted>/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "<redacted>/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 184, in http_request
    raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:5001/api/2.0/mlflow-artifacts/artifacts/10/139579893a674993ae2a2f2ac049d916/artifacts/mlflow_test.py failed with exception HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/10/139579893a674993ae2a2f2ac049d916/artifacts/mlflow_test.py (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

#### Tracking server logs
```
mlflow_server  | 2022/12/08 11:31:49 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
mlflow_server  | Traceback (most recent call last):
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
mlflow_server  |     response = self.full_dispatch_request()
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
mlflow_server  |     rv = self.handle_user_exception(e)
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
mlflow_server  |     rv = self.dispatch_request()
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
mlflow_server  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 452, in wrapper
mlflow_server  |     return func(*args, **kwargs)
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 522, in wrapper
mlflow_server  |     return func(*args, **kwargs)
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 928, in _list_artifacts
mlflow_server  |     artifact_entities = _list_artifacts_for_proxied_run_artifact_root(
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 452, in wrapper
mlflow_server  |     return func(*args, **kwargs)
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 965, in _list_artifacts_for_proxied_run_artifact_root
mlflow_server  |     for file_info in artifact_destination_repo.list_artifacts(artifact_destination_path):
mlflow_server  |   File "/home/.venv/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 44, in list_artifacts
mlflow_server  |     url, tail = self.artifact_uri.split(endpoint, maxsplit=1)
mlflow_server  | ValueError: not enough values to unpack (expected 2, got 1)
```

#### Screenshot UI
When browsing to the experiment in the UI, the `Artifacts` tab shows the below error:
![image](https://user-images.githubusercontent.com/41334387/206436947-0d12ead3-dc2e-47c5-9f33-726f7eb579de.png)

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
