### ISSUE TITLE
[SETUP-BUG] Tensorflow-macos not compatible with development environment for MLFLOW on Mac (Apple M1)

### ISSUE THREAD

**Issue by adekunleoajayi** [mlflow/mlflow#8114]
### System information

- **OS Platform and Distribution**: Mac (Apple M1)
- **MLflow installed from**: source
- **MLflow version**: 2.2.3.dev0
- **Python version**: 3.8
- **conda**: 23.1.0

### Code to reproduce issue

Conda.yml for creating the environment.

``` yml
name: mlflow-dev-env
channels:
    - apple
    - conda-forge
dependencies:
    - python=3.8.13
    - pip>=19.0
    - tensorflow-deps=2.10.0
    - pip:
        - tensorflow-macos==2.11.0
        - tensorflow-metal==0.7.1

```
Create environment
```bash
conda env create -f mlflow-dev-env.yml
```

Clone repo
```bash
git clone mlflow_git_url
git submodule update --init --recursive
cd mlflow
```

Installation of the library for development and testing.
```bash
pip install -e '.[extras]' 
pip install -r requirements/dev-requirements.txt
pip install -e tests/resources/mlflow-test-plugin tests
pip install pytest
```

Run pytest
```bash
pytest tests/tensorflow
```

### Describe the problem

Almost all the TensorFlow tests failed. 
<img width="1590" alt="Screenshot 2023-03-28 at 15 04 57" src="https://user-images.githubusercontent.com/12529807/228245588-42a6abf7-0ea0-4027-9e45-65e5fc3104a1.png">
