### ISSUE TITLE
[FR] Add boto3 to the MLFlow docker image

### ISSUE THREAD

**Issue by asolimando** [mlflow/mlflow#8342]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

According to [boto3 license](https://github.com/boto/boto3/blob/develop/LICENSE), there should be no issues adding the library to the official docker image, so that s3-based functionalities can be supported out-of-the-box, without having to extend the docker image in downstream projects.

### Motivation

> #### What is the use case for this feature?
Support s3-based functionalities in the standard docker image.

> #### Why is this use case valuable to support for MLflow users in general?
I'd say so, everyone needing s3-based model/artifact storage now has to extend the image, which is easy to do but it's annoying (you need an image registry most of the time, etc.)

> #### Why is this use case valuable to support for your project(s) or organization?
Avoid maintaining a docker image just for adding a library, without which part of the basics functionalities of MLFlow are not available

> #### Why is it currently difficult to achieve this use case?
Because the docker image can't be modified "on the fly", you have to derive and maintain your own image just for the missing `boto3` library.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @asolimando, boto3 is deliberately excluded from the MLflow Server Docker image in order to keep dependencies minimal. Thank you for using MLflow!

**Comment by hawk-roman-rey** [comment]
Hi @dbczumar, what would be the official way of installing such extra dependencies like boto3 while using the official MLFLOW docker image?

**Comment by SebastianScherer88** [comment]
@dbczumar it would be useful if you offered a version of the mlflow docker image that includes boto3, as the official mlflow image to run the tracking server should include the deps required to support the remote S3 artifact storage configuration that is documented [here](https://www.mlflow.org/docs/latest/tracking.html#mlflow-tracking-server-optional) and [here](https://www.mlflow.org/docs/latest/tracking/server.html#remote-artifacts-store)

@hawk-roman-rey a hacky way - if you are running this on kubernetes - is to simply include the pip install of boto3 in your command spec:
```
...
containers:
        - name: mlflow-tracking-server
          image: ghcr.io/mlflow/mlflow:v2.17.0
          imagePullPolicy: Always
          # use local storage for meta data and artifacts to start off
          command: ["/bin/sh","-c"]
          args: ["**pip install boto3** && mlflow server --backend-store-uri /mlflow --default-artifact-root s3://bettmensch-ai-artifact-repository/mlflow --host 0.0.0.0 --port 5000"]
          ports:
            - name: tracking-server
              containerPort: 5000
```

otherwise you can just build an image on top of the official one with an additional line ~ `RUN pip install boto3`
