### ISSUE TITLE
[DOC-FIX] Packaging Training Code in a Conda Environment Tutorial - Text does not fit to code

### ISSUE THREAD

**Issue by sebastianfastert** [mlflow/mlflow#8388]
### Willingness to contribute

Yes. I would be willing to contribute a document fix with guidance from the MLflow community.

### URL(s) with the issue

https://mlflow.org/docs/latest/tutorials-and-examples/tutorial.html#id7

### Description of proposal (what needs changing)

In the Text it says:
```
The sklearn_elasticnet_wine/MLproject file specifies that the project has the dependencies located in a Conda environment file called conda.yaml
```

The corresponding `MLProject` file is:

```
name: tutorial

python_env: python_env.yaml

entry_points:
  main:
    parameters:
      alpha: {type: float, default: 0.5}
      l1_ratio: {type: float, default: 0.1}
    command: "python train.py {alpha} {l1_ratio}"
```

I'm new to mlflow, but I think the text does not describe what happens in the code. Either the code should be changed to use `conda_env` or the text should state, that a `python_env.yaml` file needs to be created not a conda env file.
