### ISSUE TITLE
[BUG] _MLFLOW_SERVER_ARTIFACT_DESTINATION (for proxied artifact storage access) does not work with mlflow server

### ISSUE THREAD

**Issue by adekunleoajayi** [mlflow/mlflow#8858]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow: 2.4.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac M1
- **Python version**: 3.8.16

### Describe the problem

I am using mlflow server with wsgi basic auth in order to provide basic authentication for the tracking server. 

Following the specification for environment variables used for communication between mlflow cli and gunicorn processes([see here](https://github.com/mlflow/mlflow/blob/master/mlflow/server/__init__.py)), backend and artifact stores were declared as _MLFLOW_SERVER_FILE_STORE and _MLFLOW_SERVER_ARTIFACT_ROOT respectively, and this worked fine as expected. 

**The issue** 

In order to enable the server with **proxied artifact storage access**, I declared the artifacts_destination as _MLFLOW_SERVER_ARTIFACT_DESTINATION but this does not work. 

Artifact Location is expected to be preceded by **mlflow-artifacts:/** but it's not. See attached figure.

I believe that _MLFLOW_SERVER_ARTIFACT_DESTINATION is not detected within the flask application and the artifact_store_url is propagated.

<img width="1418" alt="Screenshot 2023-06-27 at 15 28 51" src="https://github.com/mlflow/mlflow/assets/12529807/090ac703-c536-4add-afab-2c8ac83211ef">

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

1 - mlflow_auth.py
```
from mlflow.server import app as mlflow_app
from wsgi_basic_auth import BasicAuth

app = BasicAuth(mlflow_app)

```

2 - entrypoint.sh
```
#!/bin/bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

export PORT=8080
export HOST=0.0.0.0

export WSGI_AUTH_CREDENTIALS="${MLFLOW_TRACKING_USERNAME}:${MLFLOW_TRACKING_PASSWORD}"
# export _MLFLOW_SERVER_ARTIFACT_ROOT="${MLFLOW_ARTIFACT_URL}" # For --no-serve-artifacts 
export _MLFLOW_SERVER_ARTIFACT_DESTINATION="${MLFLOW_ARTIFACT_URL}" # For proxied artifact storage access
export _MLFLOW_SERVER_FILE_STORE="${MLFLOW_DATABASE_URL}"

exec gunicorn -b "${HOST}:${PORT}" mlflow_auth:app
```

3 - requirements.txt

```
boto3==1.26.16
gunicorn==20.0.4
mlflow==2.4.1
psycopg2==2.9.3
wsgi-basic-auth==1.1.0
```

4 - Dockerfile
```
FROM python:3.8
RUN pip install --upgrade pip
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY mlflow_auth.py /app/mlflow_auth.py
ADD ./entrypoint.sh /app

ENTRYPOINT ["bash", "entrypoint.sh"]
```

5 - docker-compose.yml
```
version: '3.3'
services:
    remote-mlflow-server:
        build:
            context: .
        environment:
            - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
            - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
            - MLFLOW_DATABASE_URL=${MLFLOW_DATABASE_URL}
            - MLFLOW_ARTIFACT_URL=${MLFLOW_ARTIFACT_URL}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        image: remote-mlflow-server:latest
        ports:
            - "8080:8080"
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
