### ISSUE TITLE
Enable rules in `flake8-pytest-style`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9028]
Enable the following rules in https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt:

- [x] PT001
- [x] PT006
- [x] PT007
- [x] PT009
- [x] PT010
- [ ] PT012
- [x] PT018
- [x] PT023
- [x] PT026

## Settings

```toml
[tool.ruff.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false
```
