### ISSUE TITLE
Fix indentation in example yaml config for gateway

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9099]
Fix this part:

https://github.com/mlflow/mlflow/blob/1b384da05d4dca38f23f9090b93e053b9f4bbed7/docs/source/gateway/index.rst#L354-L350

```
    routes:
        - name: completions
          type: chat/completions
          model:
            provider: openai
            name: gpt-3.5-turbo
            config:
              openai_api_base: https://api.openai.com/v1
              openai_api_key: $OPENAI_API_KEY
```

to:

```
    routes:
      - name: completions
        type: chat/completions
        model:
          provider: openai
          name: gpt-3.5-turbo
          config:
            openai_api_base: https://api.openai.com/v1
            openai_api_key: $OPENAI_API_KEY
```
