### ISSUE TITLE
[BUG] problems using example mlflow artifacts docker-compose 

### ISSUE THREAD

**Issue by girdevstack** [mlflow/mlflow#9205]
@dbczumar Sorry to drop this in here, but since it's closely related I didn't really want to open a new issue. Is the expectation that the docker-compose.yml in [examples/mlflow_artifacts](https://github.com/mlflow/mlflow/blob/master/examples/mlflow_artifacts/docker-compose.yml) should work as is? I have to add several things to the tracking server to get it to both be able to push to the artifacts server and also display artifacts/models in the MLflow UI @ port 5000. If I change nothing, I am able to write to the S3 through the tracking server container but is not able to retrieve from that container because the service name isn't being resolved from the `default-artifact-root`. I am able to `exec` into the tracking server and ping using the service name artifacts-server fine, but the mlflow server itself doesn't seem to be able to handle the resolution on the docker network. 

If I understand the architecture correctly the tracking server should be interacting with the artifacts server, which is what communicates with the S3/Minio artifact store so that the secrets to S3 are managed by that container. Other examples I see (such as those above) do not run an additional container for the artifacts-server. 

Which is the better practice? Does it even  matter really? Is something broken somewhere that is preventing the example compose file from working as it currently is written?

Thank you for any pointers you can provide :smile:

_Originally posted by @girdevstack in https://github.com/mlflow/mlflow/issues/6942#issuecomment-1656317140_

**Comment by girdevstack** [comment]
I was able to get it working by setting the default-artifact-root to the host I was running this all on, and also providing the tracking server the creds for minio/S3, which I suspect circumvents the entire point of the artifact server being there at all. What is the recommended configuration for this type of architecture?

**Comment by WeichenXu123** [comment]
I want to know your use case, usually I think we can use a simpler architecture: run only one mlflow server that serves both artifacts and mlflow tracking. This is easier to config. you can just run

```
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://user:password@postgres:5432/db
      --artifacts-destination s3://bucket
```
to start server. Does this simplified architecture address your use case ?

**Comment by girdevstack** [comment]
Hi @WeichenXu123 thanks for your response. 

I'll be hosting this in a lab environment that probably will only typically see somewhere in the scale of a few dozen users. The very most I can imagine ever trying to use this would still be no more than maybe 200 people?

If this more simple configuration works well for our scale I'm content with it, I spun up and used a simple test notebook and things look good in the MLflow UI now. 

But I did notice that the creator field isn't getting populated in the model registry which probably make sense because there isn't any auth in place at the moment. Is that something that would be resolved by incorporating the basic auth work that has been added recently, or is that something that can also be set with some method in the mlflow python api? I searched around the documents and don't see an obvious way to set that like the tracking uri, experiment name, and tags.

Thanks again for your help :)

**Comment by WeichenXu123** [comment]
> I'll be hosting this in a lab environment that probably will only typically see somewhere in the scale of a few dozen users. The very most I can imagine ever trying to use this would still be no more than maybe 200 people

This use-case, the simplified architecture I mentioned above should work fine 

For auth related issues, you can refer to doc here https://mlflow.org/docs/latest/auth/index.html

**Comment by girdevstack** [comment]
Just to clarify in order to have some value logged for the model registry "creator" is to use the MLflow auth framework?

**Comment by WeichenXu123** [comment]
>  in order to have some value logged for the model registry "creator" the MLflow auth framework has to be used?

I don't think so, why it cannot be logged without auth ? do you have repro code ?

**Comment by girdevstack** [comment]
Sure no problem! 



<details><summary>docker-compse.yml</summary>

```yml  

version: "3"
services:
  minio:
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      # these need to be set somewhere, probably strongly if you don't
      # set them the default value of minioadmin is set to both
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 10s
      retries: 5
    # Note there is no bucket by default
    command: server /data --console-address ":9001"

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 user password &&
      if ! mc ls minio | grep --quiet bucket; then
        mc mb minio/bucket
      else
        echo 'bucket already exists'
      fi
      "
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  tracking_server:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      - postgres
     # - artifacts_server
    expose:
      - "5000"
    ports:
      # MLflow UI is available at http://localhost:5000
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: "user"
      AWS_SECRET_ACCESS_KEY: "password"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://user:password@postgres:5432/db
      --artifacts-destination s3://bucket
      --gunicorn-opts "--log-level debug"

```
</details>


To use this you'll need to update the MLFLOW_TRACKING_URI variable to whatever system you run the dockerized MLflow on. 

I would expect that the call to `mlflow.sklearn.log_model()` would implicitly log something (perhaps the user of the system I'm on for this like jupyter) for the `Creator` field in the UI but it does not. I looked through the docs and didn't see any means of setting that field manually, so I'm not sure how it is done without basic auth implemented.

<details><summary>mlflow_model_registration.ipynb</summary>

### Cell 1

``` python

# shamelessly copied from some example code in the MLflow repo 
# and repurposed for demo/documentation

# define and save model
import numpy as np
import pickle

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# source: https://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html

# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

# Use only one feature
diabetes_X = diabetes_X[:, np.newaxis, 2]

# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

# Split the targets into training/testing sets
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]


def print_predictions(m, y_pred):
    # The coefficients
    print("Coefficients: \n", m.coef_)
    # The mean squared error
    print("Mean squared error: %.2f" % mean_squared_error(diabetes_y_test, y_pred))
    # The coefficient of determination: 1 is perfect prediction
    print("Coefficient of determination: %.2f" % r2_score(diabetes_y_test, y_pred))


# Create linear regression object
lr_model = linear_model.LinearRegression()

# Train the model using the training sets
lr_model.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = lr_model.predict(diabetes_X_test)
print_predictions(lr_model, diabetes_y_pred)

# save the model in the native sklearn format
filename = "test_lr_model.pkl"
pickle.dump(lr_model, open(filename, "wb"))
```

### Cell 2

```python 

# load in the saved scikit model and register it with MLflow

import mlflow
from mlflow.models.signature import infer_signature
import numpy as np
from sklearn import datasets

# load the model into memory
loaded_model = pickle.load(open(filename, "rb"))

MLFLOW_TRACKING_URI = {update to host/endpoint where dockerized MLflow is running}

# create a signature for the model based on the input and output data
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)
diabetes_X = diabetes_X[:, np.newaxis, 2]
signature = infer_signature(diabetes_X, diabetes_y)

# log and register the model using MLflow scikit-learn API
# mlflow.set_tracking_uri("sqlite:///mlruns.db")

mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
reg_model_name = "SklearnLinearRegression"
artifact_path = "sk_learn"
mlflow.set_experiment(reg_model_name + "/" + artifact_path)
print("--")
mlflow.sklearn.log_model(
    loaded_model,
    artifact_path,
    serialization_format="cloudpickle",
    signature=signature,
    registered_model_name=reg_model_name,
)
```
### Cell 3

```python 
# load the model from the Model Registry and score
#model_uri = f"/sk_learn/{reg_model_name}/1"
model_uri = f"models:/SklearnLinearRegression/1"
#s3://bucket/path/to/model
a_new_loaded_model = mlflow.sklearn.load_model(model_uri)
print("--")

# Make predictions using the testing set
diabetes_y_pred = a_new_loaded_model.predict(diabetes_X_test)
print_predictions(a_new_loaded_model, diabetes_y_pred)
```
</details>


Thanks again for all your help!
