### ISSUE TITLE
MLFLOW installation Failed on kubernetes

### ISSUE THREAD

**Issue by kavita1205** [mlflow/mlflow#9487]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**: 2.6.0
- **Python version**:

### Code to reproduce issue

Hi Team,

I am trying to install mlflow application using latest version i.e. v2.6.0 in our kubernetes cluster but mlflow becomes inaccessible.

First I have created Dockerfile and below is the code:
```
FROM ghcr.io/mlflow/mlflow:v2.6.0

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
RUN pip install PyMySQL
```
After this I have build this docker file and created a custom image i.e. v2.6.7.

Post that, I have created helm chart where I am using above custom image. Below is the code for Deployment.yaml , secrets.yaml and service.yaml

Deployment.yaml
```
  {{- $artifactCommandPrefix := "default-artifact-root" }}
{{- $artifactCommand := printf "--%s=./mlruns" $artifactCommandPrefix }}

{{- if .Values.artifactRoot.proxiedArtifactStorage }}
  {{- $artifactCommandPrefix = "artifacts-destination" }}
  {{- $artifactCommand = printf "--%s=./mlartifacts" $artifactCommandPrefix }}
{{- end }}

{{- if .Values.artifactRoot.s3.enabled }}
  {{- $artifactCommand = printf "--%s=s3://%s/%s" $artifactCommandPrefix .Values.artifactRoot.s3.path .Values.artifactRoot.s3.bucket }}
{{- end }}

{{- $dbConnectionDriver := "" }}
{{- if and .Values.backendStore.mysql.enabled .Values.backendStore.mysql.driver }}
  {{- $dbConnectionDriver = printf "+%s" .Values.backendStore.mysql.driver }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Values.k8sNamespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "mlflow.docker-login-cred" . }}
      serviceAccountName: {{ include "mlflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.docker.image }}:{{ .Values.docker.tag }}"
          imagePullPolicy: {{ .Values.docker.pullPolicy }}
          command: ["mlflow"]
          args:
            - server
            - --host=0.0.0.0
            - --port={{ .Values.service.port }}
            - --backend-store-uri=mysql{{ $dbConnectionDriver }}://$(MYSQL_USERNAME):$(MYSQL_PWD)@$(MYSQL_HOST):$(MYSQL_TCP_PORT)/$(MYSQL_DATABASE)
            - --gunicorn-opts="--log-level warning"
            - {{ $artifactCommand }}
          {{- if .Values.artifactRoot.proxiedArtifactStorage }}
            - --serve-artifacts
          {{- end }}
          {{- if .Values.serviceMonitor.enabled }}
            - --expose-prometheus=/mlflow/metrics
          {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.port }}
          # {{- with .Values.livenessProbe }}
          #   {{- toYaml . | nindent 12 }}
          # {{- end }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.port }}
          # {{- with .Values.readinessProbe }}
          #   {{- toYaml . | nindent 12 }}
          # {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MLFLOW_VERSION
              value: "2.6.0"
          {{- range $key, $value := .Values.extraEnvVars }}
            - name: {{ upper $key }}
              value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "mlflow.fullname" . }}-env-configmap
            - secretRef:
                name: {{ template "mlflow.fullname" . }}-env-secret
          {{- range .Values.extraSecretNamesForEnvFrom }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (and .Values.backendStore.mysql.enabled (or .Values.backendStore.databaseConnectionCheck .Values.backendStore.databaseMigration) ) .Values.extraVolumes }}
      volumes:
        {{- if and .Values.backendStore.mysql.enabled .Values.backendStore.databaseConnectionCheck }}
        - name: dbchecker
          configMap:
            name: {{ template "mlflow.fullname" . }}-dbchecker
            defaultMode: 0777
        {{- end }}
        {{- if and .Values.backendStore.mysql.enabled .Values.backendStore.databaseMigration }}
        - name: migrations-config
          configMap:
            name: {{ template "mlflow.fullname" . }}-migrations
        {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

```
service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Values.k8sNamespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}

```

secrets.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-env-secret
  namespace: {{ .Values.k8sNamespace }}
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ARTIFACTORY_API_KEY: {{ .Values.artifactory.api_key | quote | b64enc}}
  MYSQL_USERNAME: {{ required "mysql user must be specified" .Values.backendStore.mysql.user | b64enc }}
  MYSQL_PWD: {{ required "mysql password must be specified" .Values.backendStore.mysql.password | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.artifactRoot.s3.AccessKeyId | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.artifactRoot.s3.SecretAccessKey | b64enc }}
```
values.yaml
```

replicaCount: 1
docker:
  image: XXXX.corp.xxxx.com/XXXX-XX-docker/mlflow
  pullPolicy: Always
  tag: v2.6.7

imagePullSecrets: []

k8sNamespace: autxxxxx

nameOverride: ""

fullnameOverride: "mlflow"

imageCredentials:
    registry: xxxxx.corp.xxxx.com
    username: service-xxxx
    password: xxxxxxxxxx

artifactory:
    api_key: xxxxxxx

serviceAccount:
  create: true
  annotations: {}
  name: "mlflow"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  name: http
  annotations: {}

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true

  postgres:
    enabled: false
    host: ""
    port: 5432
    database: ""
    user: ""
    password: ""
    driver: ""

  mysql:
    enabled: true
    host: "mysql-headless.automotive.svc.cluster.local"
    port: 3306
    database: "xxxx"
    user: "xxx"
    password: "xxxx"
    driver: "pymysql"

artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: "automotive-artifacts"
    path: "xxxx.corp.xxxx.com:9000"
    AccessKeyId: "xxxx"
    SecretAccessKey: "xxxx"

extraArgs: {}

extraFlags: []

extraEnvVars:
  # MinIO configuration
  MLFLOW_S3_IGNORE_TLS: true
  MLFLOW_S3_ENDPOINT_URL: https://xxxx.corp.xxx.com:9000
  MINIO_ROOT_USER: 'xxxx-xxx-user'
  MINIO_ROOT_PASSWORD: 'xxx-password'
  # MINIO_STORAGE_USE_HTTPS: False
  MINIO_SERVER_URL: 'https://xxxxx.corp.xxx.com'
  MINIO_PORT: 9000
  MLFLOW_BUCKET_NAME: "xxx-artifacts"

extraSecretNamesForEnvFrom: []

ingress:
  enabled: true
  className: xxx-lv-nginx
  # annotations:
  #   kubernetes.io/ingress.class: xx-lv-nginx
  hosts:
    - host: xx-x-xxx.corp.xxxx.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: "mlflow"
            servicePort: "5000"          
  tls:
    - secretName: tls-ingress-mlflow-secret
      hosts:
        - xxxx-xxxx-xxxx.corp.xxxx.com

resources:
  limits: 
    cpu: 1000m
    memory: 5500Mi
  requests: 
    cpu: 1000m
    memory: 5500Mi

serviceMonitor:
  enabled: true
  useServicePort: false
  namespace: monitoring
  interval: 30s
  telemetryPath: /metrics
  labels:
    release: prometheus
  timeout: 10s
  targetLabels: []

  metricRelabelings: []

nodeSelector: 
  flowapp: "true"
  datacenter: "las1"

tolerations: []

affinity: {}

initContainers: []

extraContainers: []

extraVolumes: []

extraVolumeMounts: []

livenessProbe: {}
  # initialDelaySeconds: 500
  # periodSeconds: 10
  # timeoutSeconds: 1
  # failureThreshold: 3

# -- Readiness probe configurations. Please look to [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes).
readinessProbe: {}
  # initialDelaySeconds: 500
  # periodSeconds: 10
  # timeoutSeconds: 1
  # failureThreshold: 3

```

### Describe the problem

Hi Team,

I am trying to install mlflow application using latest version i.e. v2.6.0 in our kubernetes cluster but mlflow becomes inaccessible.
After installing helm chart, mlflow pod is showing running but when I am unable to access it via UI.

```
mlflow-76db8cb58c-phw95                            1/1     Running   0          15m
```
On further troubleshooting, I found issue at pod level where If I am running "kubectl exec command "
```
kubectl exec -it mlflow-76db8cb58c-phw95 -- /bin/bash
root@mlflow-76db8cb58c-phw95:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@mlflow-76db8cb58c-phw95:/# ps -ef|more
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  5 15:38 ?        00:00:01 /usr/local/bin/python /usr/local/bin/mlflow server --
host=0.0.0.0 --port=5000 --backend-store-uri=mysql+pymysql://xxx:xxxx@mysql-headless.auto
motive.svc.cluster.local:3306/xxx --gunicorn-opts="--log-level warning" --artifacts-destination=
s3://xxx.corp.xxxx.com:9000/x-artifxx --serve-artifacts --expose-prometheus=/mlflow/metrics
root          22       0  0 15:39 pts/0    00:00:00 /bin/bash
root          29      22  0 15:39 pts/0    00:00:00 ps -ef
root          30      22  0 15:39 pts/0    00:00:00 more
```

Can someone please help me why I am not able to access mlflow application in my kubernetes cluster.

**Comment by BenWilson2** [comment]
Are you able to see the container logs running in the pod? Does anything stand out?
```bash
kubectl logs -f mlflow-76d8cb58c-phw95
```

Are you able to ping the running pod from the machine you're trying to access the UI from?

**Comment by BenWilson2** [comment]
Does a previous version of MLflow install correctly? Say, 2.2.x?

**Comment by kavita1205** [comment]
The problem is If I am directly (instead of creating custom image) using mlflow image i.e. version 2.x.x in my helm chart and then I am getting pymysql module not installed. And due to this reason I am creating custom image where I am installing pymysql  Module. Hence none of the version is working in our cluster.

**Comment by kavita1205** [comment]
One more thing, if I simply use mlflow 2.6.0 and deleting pymysql argument then mlflow is accessible but the important thing is we need pymysql argument. You can check my deployment.yaml.

**Comment by BenWilson2** [comment]
I would try ensuring that both of these libraries (and the required db installing of mysql or mariadb) all play nicely together in a docker container and that you can access the functionality that you need from that pristine environment. If there are no issues, then getting visibility into the pod build / start process is probably the best bet.

**Comment by kavita1205** [comment]
@BenWilson2 Thanks for your response. I am just explaining again what I did.

I am using mysql as database which is running as a pod on remote server and minio as artifact storage. 
Now, If I use below code in my helm chart, then I am getting error that pymysql module is not installed in pod logs.
```
docker:
  image: ghcr.io/mlflow/mlflow
  pullPolicy: Always
  tag: v2.6.0
```
```
command: mlflow server --
host=0.0.0.0 --port=5000 --backend-store-uri=mysql+pymysql://xxx:xxxx@mysql-headless.auto
motive.svc.cluster.local:3306/xxx --gunicorn-opts="--log-level warning" --artifacts-destination=
s3://xxx.corp.xxxx.com:9000/x-artifxx --serve-artifacts --expose-prometheus=/mlflow/metrics
```

As suggested #8820 issue, To fix pymysql module issue, I am using below docker file and creating a custom image where pymysql is installed along with mlflow image. But, with this, I am seeing no logs are being generated in my pod logs and also,even not able to access mlflow UI.
```
Dockerfile
FROM ghcr.io/mlflow/mlflow:v2.6.0

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
RUN pip install PyMySQL
```
After build, I am using below code
```
docker:
  image: artifacts.corp.com/xxxx-xx-docker/mlflow
  pullPolicy: Always
  tag: v2.6.7
```
```  
command: mlflow server --
host=0.0.0.0 --port=5000 --backend-store-uri=mysql+pymysql://xxx:xxxx@mysql-headless.auto
motive.svc.cluster.local:3306/xxx --gunicorn-opts="--log-level warning" --artifacts-destination=
s3://xxx.corp.xxxx.com:9000/x-artifxx --serve-artifacts --expose-prometheus=/mlflow/metrics
```

Can you please help me here how this can be fixed now or what I need to do such that mlflow can be accessed easily.

**Comment by kavita1205** [comment]
@BenWilson2 @serena-ruan 
Can someone help me here. I am trying to implement in mlflow in our production cluster where database is mysql and artifactory is minio being configured.

**Comment by serena-ruan** [comment]
Hi @kavita1205 Could you try changing `--log-level debug` to see if there's any logs generated?
Also, could you try generating a docker-compose.yml file to repro the problem?

**Comment by kavita1205** [comment]
@serena-ruan  we have created custom image v2.6.2 and as suggested by you, I have created below docker-compose.yaml, and  command "sudo docker-compose up" and with this, I am able to see mlflow application up and running.

In our case in production kubernetes cluster, we have two nodes out of which, on one node we have mysql is running and on other node, we are trying to install mlflow. Here, If I am using the same above configuration(Docker-compose.yaml) and same custom image v2.6.2 then mlflow pod is running but neither we are unable to access application, nor logs are being generated.

I have also tested mlflow pod connectivity with mysql via running ping command from mlflow pod. It seems to be fine to me.

Can you please help us. I am sharing all configurations below.

Dockerfile
```
FROM ghcr.io/mlflow/mlflow:v2.6.0

RUN apt-get update && apt-get install -f 
RUN apt-get install -y gcc default-libmysqlclient-dev build-essential python3-mysqldb 
RUN pip3 install mysql-connector-python mysql-client pymysql
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iputils-ping

```
Docker-compose.yaml
```
version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'aut***'
      MYSQL_USER: 'au****'
      MYSQL_PASSWORD: 'au***'
      MYSQL_ROOT_PASSWORD: 'au*****'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  mlflow_server:
    restart: always
    image: artifacts.corp.****.com/***-ml-docker/mlflow:v2.6.2
    container_name: mlflow_server
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:${MINIO_PORT}
      - MLFLOW_S3_IGNORE_TLS=true
    command:
      - /bin/sh
      - -c
      - |
        mlflow server --host=0.0.0.0 --port=${MLFLOW_PORT} --backend-store-uri=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_TCP_PORT}/${MYSQL_DATABASE} --gunicorn-opts="--log-level warning" --serve-artifacts --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
```

.env
```
MYSQL_DATABASE=au****
MYSQL_USER=au****
MYSQL_PASSWORD=au****
MYSQL_ROOT_PASSWORD=au****
MYSQL_HOST=db
MYSQL_TCP_PORT=3306


# MLflow configuration
MLFLOW_PORT=5000
MLFLOW_BUCKET_NAME=au****-artifacts

# MinIO access keys - these are needed by MLflow
MINIO_ACCESS_KEY=ei******y
MINIO_SECRET_ACCESS_KEY=sBDi********BngkS

# MinIO configuration
MINIO_ROOT_USER=*****-artifacts-user
MINIO_ROOT_PASSWORD=****-artifacts-password
MINIO_ADDRESS=mlminioprd.corp.com:9000
MINIO_STORAGE_USE_HTTPS=False
MINIO_PORT=9000
```


Configurations used for kubernetes:
values.yaml
```

replicaCount: 1
docker:
  image: artifacts.corp.com/***-ml-docker/mlflow
  pullPolicy: Always
  tag: v2.6.2

imagePullSecrets: []

k8sNamespace: au****

nameOverride: ""

fullnameOverride: "mlflow"

imageCredentials:
    registry: artifacts.corp.com
    username: service-kubeflow
    password: ******

artifactory:
    api_key: *****

serviceAccount:
  create: true
  annotations: {}
  name: "mlflow"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  name: web-port
  annotations: {}

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true

  postgres:
    enabled: false
    host: ""
    port: 5432
    database: ""
    user: ""
    password: ""
    driver: ""

  mysql:
    enabled: true
    host: "mysql-headless.au****.svc.cluster.local"
    port: 3306
    database: "au****"
    user: "au****"
    password: "au****"
    driver: "pymysql"

artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: "au****-artifacts"
    path: "mlminioprd.corp.com:9000"
    AccessKeyId: "****"
    SecretAccessKey: "****"

extraArgs: {}

extraFlags: []

extraEnvVars:
  MLFLOW_S3_IGNORE_TLS: true
  MLFLOW_S3_ENDPOINT_URL: https://mlminioprd.corp.com:9000
  MLFLOW_BUCKET_NAME: "au****-artifacts"
  MLFLOW_PORT: 5000
  # MinIO configuration
  MINIO_ROOT_USER: "au****-artifacts-u***"
  MINIO_ROOT_PASSWORD: "au****-artifacts-***"
  MINIO_ADDRESS: "mlminioprd.corp.com:9000"
  MINIO_STORAGE_USE_HTTPS: False
  MINIO_SERVER_URL: 'https://mlminioprd.corp.com'
  MINIO_PORT: 9000
  # MYSQL configuration
  MYSQL_HOST: "mysql-headless.automotive.svc.cluster.local"
  MYSQL_TCP_PORT: 3306
  MYSQL_DATABASE: "au****"
  MYSQL_PORT: 3306


extraSecretNamesForEnvFrom: []

ingress:
  enabled: true
  className: **-lv-nginx
  # annotations:
  #   kubernetes.io/ingress.class: **-lv-nginx
  hosts:
    - host: tracking-server-au****.corp.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: "mlflow"
            servicePort: "5000"          
  tls:
    - secretName: tls-ingress-mlflow-secret
      hosts:
        - tracking-server-au****.corp.com

resources:
  limits: 
    cpu: 1
    memory: 800M
  requests: 
    cpu: 1
    memory: 768M

serviceMonitor:
  enabled: true
  useServicePort: false
  namespace: monitoring
  interval: 30s
  telemetryPath: /metrics
  labels:
    release: prometheus
  timeout: 10s
  targetLabels: []

  metricRelabelings: []

nodeSelector: 
  autoflowapp: "true"
  datacenter: "las1"
  mldatanode: "true"

tolerations: []

affinity: {}

initContainers: []

extraContainers: []

extraVolumes: []

extraVolumeMounts: []

livenessProbe: 
  initialDelaySeconds: 30
  periodSeconds: 30
  # timeoutSeconds: 1
  # failureThreshold: 3

# -- Readiness probe configurations. Please look to [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes).
readinessProbe: {}
  # initialDelaySeconds: 500
  # periodSeconds: 10
  # timeoutSeconds: 1
  # failureThreshold: 3

```
```
 kubectl exec -it mlflow-6d8df4d684-8nvkc -- /bin/bash
root@mlflow-6d8df4d684-8nvkc:/# ps -ef|more
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  1 08:29 ?        00:00:01 /usr/local/bin/python /usr/local/bin/mlflow server --
host=0.0.0.0 --port=5000 --backend-store-uri=mysql+pymysql://autosense1:autosense_123@mysql-headless.auto
motive.svc.cluster.local:3306/autosensedb1 --gunicorn-opts=--log-level debug --default-artifact-root s3:/
/automotive-artifacts --serve-artifacts
root          23       0  0 08:31 pts/0    00:00:00 /bin/bash
root          29      23  0 08:31 pts/0    00:00:00 ps -ef
root          30      23  0 08:31 pts/0    00:00:00 more
```
