### ISSUE TITLE
Could not find experiment with ID 0 when using a docker-compose volume in --file-store

### ISSUE THREAD

**Issue by GuillemGSubies** [mlflow/mlflow#989]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: base miniconda image from Docker
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**:  3.7

### Describe the problem
I get the following error when trying to run an experiment: `API request to http://mlflow:5000/api/2.0/preview/mlflow/runs/create failed with code 500 != 200, retrying up to 0 more times. API response body: {"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Could not find experiment with ID 0"}`

### Source code / logs
Ok, so the problem comes when I execute `mlflow server --file-store ./some_dir --host 0.0.0.0` and I use:

```python
mlflow.set_tracking_uri("http://mlflow:5000")
with mlflow.start_run():
 ...
```
Everything works correctly. But if I do the exact same and `./some_dir` is a mounted volume in a docker-compose, it throws the error above. What I am trying to do is to store the files that should go in `./some_dir` directly in a volume that is also linked to a local minio server. 

According to the documentation, `./some_dir` must be persistent, I don't know if it has something to do with my problem. Anyhow, the volume I mount is persistent across the compose and in my local file storage.

This might be related to https://github.com/mlflow/mlflow/issues/613#issuecomment-444347119

**EDIT**: Full error traceback:

```
/opt/miniconda/lib/python3.7/site-packages/mlflow/tracking/fluent.py in start_run(run_uuid, experiment_id, source_name, source_version, entry_point_name, source_type, run_name, nested)
    146                 entry_point_name=entry_point_name,
    147                 source_type=source_type or _get_source_type(),
--> 148                 parent_run_id=parent_run_id)
    149     _active_run_stack.append(ActiveRun(active_run_obj))
    150     return _active_run_stack[-1]

/opt/miniconda/lib/python3.7/site-packages/mlflow/tracking/client.py in create_run(self, experiment_id, user_id, run_name, source_type, source_name, entry_point_name, start_time, source_version, tags, parent_run_id)
     64             source_version=source_version,
     65             tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
---> 66             parent_run_id=parent_run_id,
     67         )
     68 

/opt/miniconda/lib/python3.7/site-packages/mlflow/store/rest_store.py in create_run(self, experiment_id, user_id, run_name, source_type, source_name, entry_point_name, start_time, source_version, tags, parent_run_id)
    148             start_time=start_time, source_version=source_version, tags=tag_protos,
    149             parent_run_id=parent_run_id))
--> 150         response_proto = self._call_endpoint(CreateRun, req_body)
    151         run = Run.from_proto(response_proto.run)
    152         if run_name:

/opt/miniconda/lib/python3.7/site-packages/mlflow/store/rest_store.py in _call_endpoint(self, api, json_body)
     56         host_creds = self.get_host_creds()
     57         response = http_request_safe(
---> 58             host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
     59         js_dict = json.loads(response.text)
     60         parse_dict(js_dict=js_dict, message=response_proto)

/opt/miniconda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in http_request_safe(host_creds, endpoint, **kwargs)
     71     Wrapper around ``http_request`` that also verifies that the request succeeds with code 200.
     72     """
---> 73     response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
     74     if response.status_code != 200:
     75         base_msg = "API request to endpoint %s failed with error code " \

/opt/miniconda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in http_request(host_creds, endpoint, retries, retry_interval, **kwargs)
     56             time.sleep(retry_interval)
     57     raise MlflowException("API request to %s failed to return code 200 after %s tries" %
---> 58                           (url, retries))
     59 
     60 

MlflowException: API request to http://mlflow:5000/api/2.0/preview/mlflow/runs/create failed to return code 200 after 3 tries
```

**Comment by hanyucui** [comment]
Why not `mlflow.set_tracking_uri("http://localhost:5000")` instead?  Is `mlflow` a special domain name here? Did I miss something?

**Comment by GuillemGSubies** [comment]
I am using docker-compose and one of the services of the compose is called `mlflow`, there is where I run `mlflow server --file-store ./some_dir --host 0.0.0.0` So the main service of the compose can access to the mlflow server through `http://mlflow:5000`. Actually, if I want to get in the UI from outside, I have to use the url: `http:/hostname:port` where hostname is the name of the machine that the compose is running in and port is the external port I opened on the compose. Here is the part that corresponds to mlflow in the docker-compose.yml file:

```yaml
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile_mlflow
    ports: 
      - ${MLFLOW_PORT:-0}:5000
    networks:
      - network
    volumes:
      - ${VOLUME:-./s3}:/data
    command: 'mlflow server --file-store ./mlflow --host 0.0.0.0'
```
(here, if that `data` in volumes and the param that goes into `--file-store` are the same I get the error I explain above. If I leave it the way it is, it works but I cannot retrieve the files stored in `--file--store` because I have no way other than mounting a volume to access to it)

The Dockerfile is this:

```
FROM continuumio/miniconda3:4.5.12

RUN pip install mlflow==0.8.2

EXPOSE 5000
```
I hope now I explained properly

**Comment by hanyucui** [comment]
@GuillemGSubies Thanks for the details! Let me take a look in the weekend.

**Comment by jimthompson5802** [comment]
@GuillemGSubies  I believe I'm doing the same thing you're trying to do.  I've used this set up several times to demonstrate mlflow.  Here is my docker-compose.yaml file:
```
version: '3'

services:

# Python
  python:
    build: 
      context: .
      dockerfile: python_image/Dockerfile

    image: mlflow_py_demo

    ports:
      - "8888:8888"

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/opt/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    # command to start jupyter notebook server
    command: >
       jupyter notebook --no-browser --ip 0.0.0.0 
          --allow-root --password='' --NotebookApp.token=''
          --notebook-dir=/opt/project

# R
  r:
    build: 
      context: .
      dockerfile: mlflow_r_image/Dockerfile

    image: mlflow_r_demo

    ports:
      - "8787:8787"

    environment:
      DISABLE_AUTH:  'true'

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/home/rstudio/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"


# mlflow_tracker
  mlflow_server:
    build: 
      context: .
      dockerfile: mlflow_server/Dockerfile

    image: mlflow_server
    
    ports:
      - "5000:5000"

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/tracking:/tracking"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    command: >
      mlflow server 
        --file-store /tracking 
        --default-artifact-root /artifacts 
        --host 0.0.0.0
```

This is the high-level illustration of the set up 
![demo_environment_architecture](https://user-images.githubusercontent.com/1425269/54469699-df047a80-4771-11e9-8405-93b3d0f7beaf.png)
